import type { ScreenId } from "@/lib/model";

export type CatalogMission = {
  id: string;
  category: string;
  categoryName: string;
  title: string;
  work: string;
  measure: string;
  beneficiary: string;
  mode: "Single" | "Team" | "Swarm";
  modeNote: string;
  screen: ScreenId;
  first: boolean;
};

export const CATALOG_CATEGORIES: { id: string; name: string; beneficiary: string; modeNote: string }[] = [
  {
    "id": "A",
    "name": "Fee intelligence and savings discovery",
    "beneficiary": "Employer and employees",
    "modeNote": "Team"
  },
  {
    "id": "B",
    "name": "Employer negotiation and purchasing power",
    "beneficiary": "Employer and employees",
    "modeNote": "Team; Swarm for multiple entities"
  },
  {
    "id": "C",
    "name": "Competitive tenders and a more contestable market",
    "beneficiary": "Employer and employees",
    "modeNote": "Team; Swarm for broad tenders"
  },
  {
    "id": "D",
    "name": "Switching, portability and implementation",
    "beneficiary": "Employer and employees",
    "modeNote": "Team"
  },
  {
    "id": "E",
    "name": "Employer administration and contribution accuracy",
    "beneficiary": "Employer and employees",
    "modeNote": "Single for routine checks; Team for exceptions"
  },
  {
    "id": "F",
    "name": "Investment performance and manager diagnosis",
    "beneficiary": "Employees",
    "modeNote": "Team"
  },
  {
    "id": "G",
    "name": "Investment menu and portfolio improvement",
    "beneficiary": "Employees; employer implementation costs shown",
    "modeNote": "Team; Swarm for broad scenario analysis"
  },
  {
    "id": "H",
    "name": "Personal employee returns and retirement planning",
    "beneficiary": "Employees; incremental employer matching disclosed",
    "modeNote": "Single for explanations; Team for recommendations"
  },
  {
    "id": "I",
    "name": "Retirement transitions, tax and benefit protection",
    "beneficiary": "Employees",
    "modeNote": "Team; qualified review for legal or tax conclusions"
  },
  {
    "id": "J",
    "name": "Plan design that improves employee value",
    "beneficiary": "Employer and employees",
    "modeNote": "Team; Swarm for workforce simulations"
  },
  {
    "id": "K",
    "name": "Continuous monitoring and new mission generation",
    "beneficiary": "Employer and employees",
    "modeNote": "Single monitors; Team investigations"
  },
  {
    "id": "L",
    "name": "Proof of value, governance and accumulated intelligence",
    "beneficiary": "Employer and employees",
    "modeNote": "Team with an independent challenger"
  }
];

export const CATALOG_MISSIONS: CatalogMission[] = [
  {
    "id": "A01",
    "category": "A",
    "categoryName": "Fee intelligence and savings discovery",
    "title": "Map every fee and its payer",
    "work": "Extract contracts, factsheets, invoices and statements into one fee ledger; distinguish employer-paid, fund-paid and member-paid charges.",
    "measure": "THB/year by payer; completeness and source confidence.",
    "beneficiary": "Employer and employees",
    "mode": "Team",
    "modeNote": "Team",
    "screen": "xray",
    "first": true
  },
  {
    "id": "A02",
    "category": "A",
    "categoryName": "Fee intelligence and savings discovery",
    "title": "Benchmark fees against comparable employers",
    "work": "Compare the same policy type, assets, member count and service scope; identify defensible repricing targets.",
    "measure": "Fee gap in basis points and THB/year.",
    "beneficiary": "Employer and employees",
    "mode": "Team",
    "modeNote": "Team",
    "screen": "xray",
    "first": true
  },
  {
    "id": "A03",
    "category": "A",
    "categoryName": "Fee intelligence and savings discovery",
    "title": "Expose layered investment costs",
    "work": "Look through underlying funds, share classes, rebates and waivers; distinguish included costs from additional charges.",
    "measure": "Effective total cost without double-counting.",
    "beneficiary": "Employer and employees",
    "mode": "Team",
    "modeNote": "Team",
    "screen": "xray",
    "first": false
  },
  {
    "id": "A04",
    "category": "A",
    "categoryName": "Fee intelligence and savings discovery",
    "title": "Check actual charges against contracts",
    "work": "Reconcile invoiced and deducted fees to agreed rates, caps, exemptions and effective dates.",
    "measure": "Supported overcharge exceptions in THB.",
    "beneficiary": "Employer and employees",
    "mode": "Team",
    "modeNote": "Team",
    "screen": "xray",
    "first": false
  },
  {
    "id": "A05",
    "category": "A",
    "categoryName": "Fee intelligence and savings discovery",
    "title": "Recalculate NAV-based and tiered fees",
    "work": "Verify the valuation base, averaging method, day count, asset tiers and member counts used for billing.",
    "measure": "Calculation errors and corrected fee amounts.",
    "beneficiary": "Employer and employees",
    "mode": "Team",
    "modeNote": "Team",
    "screen": "xray",
    "first": false
  },
  {
    "id": "A06",
    "category": "A",
    "categoryName": "Fee intelligence and savings discovery",
    "title": "Recover missing rebates and credits",
    "work": "Identify contractual rebates, waivers and credits that were earned but not received; trace the rightful recipient.",
    "measure": "Recoverable amounts by beneficiary.",
    "beneficiary": "Employer and employees",
    "mode": "Team",
    "modeNote": "Team",
    "screen": "xray",
    "first": false
  },
  {
    "id": "A07",
    "category": "A",
    "categoryName": "Fee intelligence and savings discovery",
    "title": "Investigate trading and foreign-exchange costs",
    "work": "Analyze available transaction and execution data for excess turnover, spreads and currency-conversion costs.",
    "measure": "Documented costs; modeled avoidable portion.",
    "beneficiary": "Employer and employees",
    "mode": "Team",
    "modeNote": "Team",
    "screen": "xray",
    "first": false
  },
  {
    "id": "A08",
    "category": "A",
    "categoryName": "Fee intelligence and savings discovery",
    "title": "Reduce minimum and small-account charges",
    "work": "Assess fixed minimums and fragmented small accounts; identify permitted pricing or account-structure changes.",
    "measure": "Net savings after restructuring costs.",
    "beneficiary": "Employer and employees",
    "mode": "Team",
    "modeNote": "Team",
    "screen": "xray",
    "first": false
  },
  {
    "id": "A09",
    "category": "A",
    "categoryName": "Fee intelligence and savings discovery",
    "title": "Find duplicate service charges",
    "work": "Locate overlapping employer contracts, duplicate invoices and services already included elsewhere.",
    "measure": "Verified duplicate spend and removable charges.",
    "beneficiary": "Employer and employees",
    "mode": "Team",
    "modeNote": "Team",
    "screen": "xray",
    "first": false
  },
  {
    "id": "A10",
    "category": "A",
    "categoryName": "Fee intelligence and savings discovery",
    "title": "Build the prioritized savings plan",
    "work": "Rank verified opportunities by beneficiary, confidence, feasibility, effort and payback; eliminate overlapping claims.",
    "measure": "Distinct savings opportunities with owners and next actions.",
    "beneficiary": "Employer and employees",
    "mode": "Team",
    "modeNote": "Team",
    "screen": "xray",
    "first": true
  },
  {
    "id": "B01",
    "category": "B",
    "categoryName": "Employer negotiation and purchasing power",
    "title": "Prepare the renewal negotiation",
    "work": "Use comparable quotes and current results to draft the target price, evidence, concessions and negotiation sequence.",
    "measure": "Negotiation target and acceptable service floor.",
    "beneficiary": "Employer and employees",
    "mode": "Team",
    "modeNote": "Team; Swarm for multiple entities",
    "screen": "nego",
    "first": true
  },
  {
    "id": "B02",
    "category": "B",
    "categoryName": "Employer negotiation and purchasing power",
    "title": "Request asset- or headcount-tier repricing",
    "work": "Check eligibility for existing discounts and model a new tier schedule as assets or membership grow.",
    "measure": "Annual fee reduction and trigger thresholds.",
    "beneficiary": "Employer and employees",
    "mode": "Team",
    "modeNote": "Team; Swarm for multiple entities",
    "screen": "nego",
    "first": false
  },
  {
    "id": "B03",
    "category": "B",
    "categoryName": "Employer negotiation and purchasing power",
    "title": "Consolidate group-company procurement",
    "work": "Combine subsidiary purchasing requirements where permitted while preserving each fund's obligations and rights.",
    "measure": "Group savings net of coordination and migration costs.",
    "beneficiary": "Employer and employees",
    "mode": "Team",
    "modeNote": "Team; Swarm for multiple entities",
    "screen": "nego",
    "first": false
  },
  {
    "id": "B04",
    "category": "B",
    "categoryName": "Employer negotiation and purchasing power",
    "title": "Organize an employer buying group",
    "work": "Match consenting employers with compatible requirements for a permitted joint tender; keep sensitive bid data controlled.",
    "measure": "Achievable quotes versus each employer's current terms.",
    "beneficiary": "Employer and employees",
    "mode": "Team",
    "modeNote": "Team; Swarm for multiple entities",
    "screen": "nego",
    "first": false
  },
  {
    "id": "B05",
    "category": "B",
    "categoryName": "Employer negotiation and purchasing power",
    "title": "Compare pooled and standalone arrangements",
    "work": "Model the cost, governance, investment choice and service trade-offs of available structures.",
    "measure": "Three- and five-year total cost by payer.",
    "beneficiary": "Employer and employees",
    "mode": "Team",
    "modeNote": "Team; Swarm for multiple entities",
    "screen": "nego",
    "first": false
  },
  {
    "id": "B06",
    "category": "B",
    "categoryName": "Employer negotiation and purchasing power",
    "title": "Analyze bank-bundling trade-offs",
    "work": "Review documented links between PVD, payroll, lending and other bank services; compare whole-relationship economics.",
    "measure": "Net benefit after any verified repricing of linked services.",
    "beneficiary": "Employer and employees",
    "mode": "Team",
    "modeNote": "Team; Swarm for multiple entities",
    "screen": "nego",
    "first": false
  },
  {
    "id": "B07",
    "category": "B",
    "categoryName": "Employer negotiation and purchasing power",
    "title": "Reprice ancillary fund services",
    "work": "Benchmark audit, custody, registration and member-service charges where separately procurable.",
    "measure": "Savings with equivalent required service quality.",
    "beneficiary": "Employer and employees",
    "mode": "Team",
    "modeNote": "Team; Swarm for multiple entities",
    "screen": "nego",
    "first": false
  },
  {
    "id": "B08",
    "category": "B",
    "categoryName": "Employer negotiation and purchasing power",
    "title": "Claim service-level credits",
    "work": "Match documented service failures to contractual remedies and prepare a supported claim.",
    "measure": "Credits recoverable and subsequently received.",
    "beneficiary": "Employer and employees",
    "mode": "Team",
    "modeNote": "Team; Swarm for multiple entities",
    "screen": "nego",
    "first": false
  },
  {
    "id": "B09",
    "category": "B",
    "categoryName": "Employer negotiation and purchasing power",
    "title": "Negotiate overcharge refunds",
    "work": "Prepare reconciled evidence, correspondence drafts and a settlement tracker for disputed charges.",
    "measure": "Refunds actually received, tracked separately from recurring savings.",
    "beneficiary": "Employer and employees",
    "mode": "Team",
    "modeNote": "Team; Swarm for multiple entities",
    "screen": "nego",
    "first": false
  },
  {
    "id": "B10",
    "category": "B",
    "categoryName": "Employer negotiation and purchasing power",
    "title": "Negotiate durable fee protections",
    "work": "Draft price caps, discount persistence, transparent pass-through costs, portability and renewal terms.",
    "measure": "Future cost exposure under explicit scenarios.",
    "beneficiary": "Employer and employees",
    "mode": "Team",
    "modeNote": "Team; Swarm for multiple entities",
    "screen": "nego",
    "first": false
  },
  {
    "id": "C01",
    "category": "C",
    "categoryName": "Competitive tenders and a more contestable market",
    "title": "Find eligible providers and policies",
    "work": "Screen available providers against fund size, permitted policies, workforce needs and required services.",
    "measure": "Qualified market coverage and justified exclusions.",
    "beneficiary": "Employer and employees",
    "mode": "Team",
    "modeNote": "Team; Swarm for broad tenders",
    "screen": "tender",
    "first": false
  },
  {
    "id": "C02",
    "category": "C",
    "categoryName": "Competitive tenders and a more contestable market",
    "title": "Create a reusable employer requirements profile",
    "work": "Turn approved requirements into a portable profile; prepare an anonymized version for market discovery.",
    "measure": "Less repeated tender work and more relevant provider responses.",
    "beneficiary": "Employer and employees",
    "mode": "Team",
    "modeNote": "Team; Swarm for broad tenders",
    "screen": "tender",
    "first": false
  },
  {
    "id": "C03",
    "category": "C",
    "categoryName": "Competitive tenders and a more contestable market",
    "title": "Draft an outcome-based RFP",
    "work": "Specify fee disclosure, appropriate risk and performance comparisons, service standards and transfer requirements.",
    "measure": "Committee-ready RFP with measurable acceptance criteria.",
    "beneficiary": "Employer and employees",
    "mode": "Team",
    "modeNote": "Team; Swarm for broad tenders",
    "screen": "tender",
    "first": true
  },
  {
    "id": "C04",
    "category": "C",
    "categoryName": "Competitive tenders and a more contestable market",
    "title": "Coordinate authorized bid invitations",
    "work": "After approval, invite qualified providers, manage deadlines and track missing responses.",
    "measure": "Qualified bids received and response time.",
    "beneficiary": "Employer and employees",
    "mode": "Team",
    "modeNote": "Team; Swarm for broad tenders",
    "screen": "tender",
    "first": false
  },
  {
    "id": "C05",
    "category": "C",
    "categoryName": "Competitive tenders and a more contestable market",
    "title": "Normalize competing proposals",
    "work": "Put bids on the same fee, tax, asset, member-count, service and return-reporting basis.",
    "measure": "Comparable annual and multiyear total costs.",
    "beneficiary": "Employer and employees",
    "mode": "Team",
    "modeNote": "Team; Swarm for broad tenders",
    "screen": "tender",
    "first": true
  },
  {
    "id": "C06",
    "category": "C",
    "categoryName": "Competitive tenders and a more contestable market",
    "title": "Perform provider due diligence",
    "work": "Review verifiable investment process, team stability, operational capacity, service evidence and conflicts.",
    "measure": "Evidence-backed strengths, gaps and unresolved questions.",
    "beneficiary": "Employer and employees",
    "mode": "Team",
    "modeNote": "Team; Swarm for broad tenders",
    "screen": "tender",
    "first": false
  },
  {
    "id": "C07",
    "category": "C",
    "categoryName": "Competitive tenders and a more contestable market",
    "title": "Compare cost, risk, return and service trade-offs",
    "work": "Build scenarios using common assumptions and committee-approved weights; show alternatives and sensitivity.",
    "measure": "Preferred options under different priorities and risk constraints.",
    "beneficiary": "Employer and employees",
    "mode": "Team",
    "modeNote": "Team; Swarm for broad tenders",
    "screen": "tender",
    "first": false
  },
  {
    "id": "C08",
    "category": "C",
    "categoryName": "Competitive tenders and a more contestable market",
    "title": "Resolve bid ambiguities",
    "work": "Draft specific questions on hidden charges, exclusions, performance definitions and migration commitments.",
    "measure": "Clarified terms and reduction in unresolved cost exposure.",
    "beneficiary": "Employer and employees",
    "mode": "Team",
    "modeNote": "Team; Swarm for broad tenders",
    "screen": "tender",
    "first": false
  },
  {
    "id": "C09",
    "category": "C",
    "categoryName": "Competitive tenders and a more contestable market",
    "title": "Negotiate best and final offers",
    "work": "Develop controlled negotiation rounds with service and risk floors; protect confidential competing bids.",
    "measure": "Improvement from opening to final comparable offers.",
    "beneficiary": "Employer and employees",
    "mode": "Team",
    "modeNote": "Team; Swarm for broad tenders",
    "screen": "tender",
    "first": false
  },
  {
    "id": "C10",
    "category": "C",
    "categoryName": "Competitive tenders and a more contestable market",
    "title": "Prepare the committee award recommendation",
    "work": "Assemble the decision matrix, evidence, conflicts, assumptions, dissenting analysis and approval record.",
    "measure": "Reviewable recommendation with quantified employer and employee impacts.",
    "beneficiary": "Employer and employees",
    "mode": "Team",
    "modeNote": "Team; Swarm for broad tenders",
    "screen": "tender",
    "first": true
  },
  {
    "id": "D01",
    "category": "D",
    "categoryName": "Switching, portability and implementation",
    "title": "Compare staying, renegotiating and switching",
    "work": "Evaluate all three routes using consistent risk, service, cost and time assumptions.",
    "measure": "Separate employer and employee business cases.",
    "beneficiary": "Employer and employees",
    "mode": "Team",
    "modeNote": "Team",
    "screen": "switching",
    "first": true
  },
  {
    "id": "D02",
    "category": "D",
    "categoryName": "Switching, portability and implementation",
    "title": "Calculate switching payback",
    "work": "Include exit fees, transition costs, implementation costs and possible market-exposure gaps.",
    "measure": "Payback by payer; sensitivity and conditions for no switch.",
    "beneficiary": "Employer and employees",
    "mode": "Team",
    "modeNote": "Team",
    "screen": "switching",
    "first": false
  },
  {
    "id": "D03",
    "category": "D",
    "categoryName": "Switching, portability and implementation",
    "title": "Map exit rights and notice windows",
    "work": "Extract current contract provisions and applicable requirements; identify items needing qualified review.",
    "measure": "Feasible dates, documented charges and unresolved dependencies.",
    "beneficiary": "Employer and employees",
    "mode": "Team",
    "modeNote": "Team",
    "screen": "switching",
    "first": false
  },
  {
    "id": "D04",
    "category": "D",
    "categoryName": "Switching, portability and implementation",
    "title": "Check the final contract against the winning bid",
    "work": "Compare signed-form terms with approved pricing, waivers, service levels and transfer commitments.",
    "measure": "Deviations corrected before execution.",
    "beneficiary": "Employer and employees",
    "mode": "Team",
    "modeNote": "Team",
    "screen": "switching",
    "first": false
  },
  {
    "id": "D05",
    "category": "D",
    "categoryName": "Switching, portability and implementation",
    "title": "Prepare portable member and fund records",
    "work": "Validate and map authorized balances, contribution histories, policy elections and member identifiers.",
    "measure": "Accepted transfer dataset and exception list.",
    "beneficiary": "Employer and employees",
    "mode": "Team",
    "modeNote": "Team",
    "screen": "switching",
    "first": false
  },
  {
    "id": "D06",
    "category": "D",
    "categoryName": "Switching, portability and implementation",
    "title": "Compare permitted asset-transfer methods",
    "work": "Assess cash versus in-kind routes where supported, including execution costs and exposure continuity.",
    "measure": "Transition recommendation with quantified cost and risk ranges.",
    "beneficiary": "Employer and employees",
    "mode": "Team",
    "modeNote": "Team",
    "screen": "switching",
    "first": false
  },
  {
    "id": "D07",
    "category": "D",
    "categoryName": "Switching, portability and implementation",
    "title": "Plan the transition timetable",
    "work": "Coordinate notice, dealing, settlement, blackout periods, communications and reconciliation responsibilities.",
    "measure": "Operational schedule that minimizes avoidable idle periods.",
    "beneficiary": "Employer and employees",
    "mode": "Team",
    "modeNote": "Team",
    "screen": "switching",
    "first": false
  },
  {
    "id": "D08",
    "category": "D",
    "categoryName": "Switching, portability and implementation",
    "title": "Maintain contribution continuity during transfer",
    "work": "Track payroll remittances and allocation instructions through the transition.",
    "measure": "Contributions correctly received and invested; unresolved exceptions.",
    "beneficiary": "Employer and employees",
    "mode": "Team",
    "modeNote": "Team",
    "screen": "switching",
    "first": false
  },
  {
    "id": "D09",
    "category": "D",
    "categoryName": "Switching, portability and implementation",
    "title": "Reconcile transferred assets and balances",
    "work": "Match closing balances, transferred assets or cash, opening units and fees; investigate differences.",
    "measure": "Reconciled balances and supported correction requests.",
    "beneficiary": "Employer and employees",
    "mode": "Team",
    "modeNote": "Team",
    "screen": "switching",
    "first": false
  },
  {
    "id": "D10",
    "category": "D",
    "categoryName": "Switching, portability and implementation",
    "title": "Validate transition commitments",
    "work": "Check migration charges, waived fees, policy mappings and service delivery against agreed terms.",
    "measure": "Implementation closure report and any justified remedies.",
    "beneficiary": "Employer and employees",
    "mode": "Team",
    "modeNote": "Team",
    "screen": "switching",
    "first": false
  },
  {
    "id": "E01",
    "category": "E",
    "categoryName": "Employer administration and contribution accuracy",
    "title": "Reconcile payroll to fund contributions",
    "work": "Match payroll deductions, employer contributions, transfers and member allocations.",
    "measure": "Reconciliation coverage, exceptions and time saved.",
    "beneficiary": "Employer and employees",
    "mode": "Single",
    "modeNote": "Single for routine checks; Team for exceptions",
    "screen": "docs",
    "first": false
  },
  {
    "id": "E02",
    "category": "E",
    "categoryName": "Employer administration and contribution accuracy",
    "title": "Correct contribution-calculation errors",
    "work": "Check eligible salary bases, contribution rates and effective dates against verified rules.",
    "measure": "Amounts corrected for each party; corrections are not automatically savings.",
    "beneficiary": "Employer and employees",
    "mode": "Single",
    "modeNote": "Single for routine checks; Team for exceptions",
    "screen": "docs",
    "first": false
  },
  {
    "id": "E03",
    "category": "E",
    "categoryName": "Employer administration and contribution accuracy",
    "title": "Find missing or misallocated contributions",
    "work": "Identify contributions missing from member accounts or posted to the wrong member or policy.",
    "measure": "Amounts traced and restored to the rightful account.",
    "beneficiary": "Employer and employees",
    "mode": "Single",
    "modeNote": "Single for routine checks; Team for exceptions",
    "screen": "docs",
    "first": false
  },
  {
    "id": "E04",
    "category": "E",
    "categoryName": "Employer administration and contribution accuracy",
    "title": "Optimize compliant remittance operations",
    "work": "Schedule preparation, checks and payment within applicable deadlines; investigate avoidable delays.",
    "measure": "Lower processing effort and fewer delayed allocations.",
    "beneficiary": "Employer and employees",
    "mode": "Single",
    "modeNote": "Single for routine checks; Team for exceptions",
    "screen": "docs",
    "first": false
  },
  {
    "id": "E05",
    "category": "E",
    "categoryName": "Employer administration and contribution accuracy",
    "title": "Automate member onboarding checks",
    "work": "Validate eligibility, enrollment records, policy elections and authorized data before submission.",
    "measure": "Cost per enrollment and exception rate.",
    "beneficiary": "Employer and employees",
    "mode": "Single",
    "modeNote": "Single for routine checks; Team for exceptions",
    "screen": "docs",
    "first": false
  },
  {
    "id": "E06",
    "category": "E",
    "categoryName": "Employer administration and contribution accuracy",
    "title": "Process employee departures accurately",
    "work": "Prepare leaver calculations and permitted options using current fund rules and verified entitlements.",
    "measure": "Processing time, errors avoided and protected member rights.",
    "beneficiary": "Employer and employees",
    "mode": "Single",
    "modeNote": "Single for routine checks; Team for exceptions",
    "screen": "docs",
    "first": false
  },
  {
    "id": "E07",
    "category": "E",
    "categoryName": "Employer administration and contribution accuracy",
    "title": "Validate and explain member statements",
    "work": "Reconcile balances and transactions, then generate clear explanations from the verified data.",
    "measure": "Statement discrepancies resolved and fewer support requests.",
    "beneficiary": "Employer and employees",
    "mode": "Single",
    "modeNote": "Single for routine checks; Team for exceptions",
    "screen": "docs",
    "first": false
  },
  {
    "id": "E08",
    "category": "E",
    "categoryName": "Employer administration and contribution accuracy",
    "title": "Resolve routine PVD service questions",
    "work": "Answer grounded questions on fees, contributions and processes; escalate individualized advice appropriately.",
    "measure": "Resolution time, escalation quality and service cost.",
    "beneficiary": "Employer and employees",
    "mode": "Single",
    "modeNote": "Single for routine checks; Team for exceptions",
    "screen": "docs",
    "first": false
  },
  {
    "id": "E09",
    "category": "E",
    "categoryName": "Employer administration and contribution accuracy",
    "title": "Coordinate required member communications",
    "work": "Prepare targeted notices, meeting materials and training schedules through authorized channels.",
    "measure": "Administrative effort and completion rate.",
    "beneficiary": "Employer and employees",
    "mode": "Single",
    "modeNote": "Single for routine checks; Team for exceptions",
    "screen": "docs",
    "first": false
  },
  {
    "id": "E10",
    "category": "E",
    "categoryName": "Employer administration and contribution accuracy",
    "title": "Redesign the PVD operating workflow",
    "work": "Identify repeated manual work and implement approved automation with exception ownership.",
    "measure": "Hours released; actual budget reductions reported separately.",
    "beneficiary": "Employer and employees",
    "mode": "Single",
    "modeNote": "Single for routine checks; Team for exceptions",
    "screen": "docs",
    "first": false
  },
  {
    "id": "F01",
    "category": "F",
    "categoryName": "Investment performance and manager diagnosis",
    "title": "Standardize historical return data",
    "work": "Align dates, currency, annualization, distributions and net-versus-gross reporting before comparison.",
    "measure": "Comparable return series with documented limitations.",
    "beneficiary": "Employees",
    "mode": "Team",
    "modeNote": "Team",
    "screen": "bench",
    "first": false
  },
  {
    "id": "F02",
    "category": "F",
    "categoryName": "Investment performance and manager diagnosis",
    "title": "Validate the investment benchmark",
    "work": "Match the benchmark to asset mix, risk, currency and mandate; use appropriate total-return measures.",
    "measure": "Benchmark mismatch findings and corrected comparisons.",
    "beneficiary": "Employees",
    "mode": "Team",
    "modeNote": "Team",
    "screen": "bench",
    "first": false
  },
  {
    "id": "F03",
    "category": "F",
    "categoryName": "Investment performance and manager diagnosis",
    "title": "Compare policies at similar risk",
    "work": "Compare available policies with similar objectives, exposures and risk over common periods.",
    "measure": "Historical net-return gap with risk and uncertainty shown.",
    "beneficiary": "Employees",
    "mode": "Team",
    "modeNote": "Team",
    "screen": "bench",
    "first": true
  },
  {
    "id": "F04",
    "category": "F",
    "categoryName": "Investment performance and manager diagnosis",
    "title": "Test performance consistency",
    "work": "Analyze rolling periods, different start dates and available full-cycle records; account for incomplete histories.",
    "measure": "Consistency statistics and robustness to period selection.",
    "beneficiary": "Employees",
    "mode": "Team",
    "modeNote": "Team",
    "screen": "bench",
    "first": false
  },
  {
    "id": "F05",
    "category": "F",
    "categoryName": "Investment performance and manager diagnosis",
    "title": "Explain where returns came from",
    "work": "Separate fees, broad market exposure, allocation and manager decisions where data supports attribution.",
    "measure": "Return contributors and residual unexplained differences.",
    "beneficiary": "Employees",
    "mode": "Team",
    "modeNote": "Team",
    "screen": "bench",
    "first": false
  },
  {
    "id": "F06",
    "category": "F",
    "categoryName": "Investment performance and manager diagnosis",
    "title": "Compare active management with cheaper alternatives",
    "work": "Assess eligible passive or lower-cost options with comparable exposures and implementation constraints.",
    "measure": "Fee advantage and historical net-performance trade-offs.",
    "beneficiary": "Employees",
    "mode": "Team",
    "modeNote": "Team",
    "screen": "bench",
    "first": false
  },
  {
    "id": "F07",
    "category": "F",
    "categoryName": "Investment performance and manager diagnosis",
    "title": "Test evidence of manager skill",
    "work": "Assess performance beyond market and factor exposures, sample size and persistence.",
    "measure": "Strength of evidence; no assumed repeat of past outperformance.",
    "beneficiary": "Employees",
    "mode": "Team",
    "modeNote": "Team",
    "screen": "bench",
    "first": false
  },
  {
    "id": "F08",
    "category": "F",
    "categoryName": "Investment performance and manager diagnosis",
    "title": "Analyze drawdowns and recovery",
    "work": "Measure losses, downside behavior and recovery across historical stress periods.",
    "measure": "Observed loss ranges and recovery characteristics.",
    "beneficiary": "Employees",
    "mode": "Team",
    "modeNote": "Team",
    "screen": "bench",
    "first": false
  },
  {
    "id": "F09",
    "category": "F",
    "categoryName": "Investment performance and manager diagnosis",
    "title": "Detect strategy and team changes",
    "work": "Track verifiable mandate drift, portfolio changes and investment-team turnover.",
    "measure": "Reasons to reassess future suitability and monitoring intensity.",
    "beneficiary": "Employees",
    "mode": "Team",
    "modeNote": "Team",
    "screen": "bench",
    "first": false
  },
  {
    "id": "F10",
    "category": "F",
    "categoryName": "Investment performance and manager diagnosis",
    "title": "Investigate persistent underperformance",
    "work": "Combine comparable returns, costs, risks and explanations into a structured review case.",
    "measure": "Questions, remediation options and escalation thresholds.",
    "beneficiary": "Employees",
    "mode": "Team",
    "modeNote": "Team",
    "screen": "bench",
    "first": false
  },
  {
    "id": "G01",
    "category": "G",
    "categoryName": "Investment menu and portfolio improvement",
    "title": "Find gaps in the available investment menu",
    "work": "Compare workforce needs with current eligible policies and identify missing low-cost or diversified choices.",
    "measure": "Prioritized menu changes with cost and suitability rationale.",
    "beneficiary": "Employees; employer implementation costs shown",
    "mode": "Team",
    "modeNote": "Team; Swarm for broad scenario analysis",
    "screen": "designer",
    "first": false
  },
  {
    "id": "G02",
    "category": "G",
    "categoryName": "Investment menu and portfolio improvement",
    "title": "Find better cost-return-risk combinations",
    "work": "Evaluate eligible alternatives under consistent forward-looking assumptions and robust risk constraints.",
    "measure": "A set of trade-offs; no single universal best fund.",
    "beneficiary": "Employees; employer implementation costs shown",
    "mode": "Team",
    "modeNote": "Team; Swarm for broad scenario analysis",
    "screen": "designer",
    "first": false
  },
  {
    "id": "G03",
    "category": "G",
    "categoryName": "Investment menu and portfolio improvement",
    "title": "Improve portfolio diversification",
    "work": "Analyze look-through exposures and feasible combinations; account for correlation instability.",
    "measure": "Diversification proposals with scenario risk estimates.",
    "beneficiary": "Employees; employer implementation costs shown",
    "mode": "Team",
    "modeNote": "Team; Swarm for broad scenario analysis",
    "screen": "designer",
    "first": false
  },
  {
    "id": "G04",
    "category": "G",
    "categoryName": "Investment menu and portfolio improvement",
    "title": "Remove redundant fund exposures",
    "work": "Identify overlapping holdings and duplicated strategies across the employee's selected policies.",
    "measure": "Simpler alternatives and any verified fee reductions.",
    "beneficiary": "Employees; employer implementation costs shown",
    "mode": "Team",
    "modeNote": "Team; Swarm for broad scenario analysis",
    "screen": "designer",
    "first": false
  },
  {
    "id": "G05",
    "category": "G",
    "categoryName": "Investment menu and portfolio improvement",
    "title": "Compare life-path and target-date approaches",
    "work": "Evaluate glide paths, costs, assumptions and suitability for different member groups.",
    "measure": "Long-horizon scenarios and implementation requirements.",
    "beneficiary": "Employees; employer implementation costs shown",
    "mode": "Team",
    "modeNote": "Team; Swarm for broad scenario analysis",
    "screen": "designer",
    "first": false
  },
  {
    "id": "G06",
    "category": "G",
    "categoryName": "Investment menu and portfolio improvement",
    "title": "Design suitable default choices",
    "work": "Model defaults for verified member needs within applicable rules and provider capabilities.",
    "measure": "Default-policy proposal, member impact and review triggers.",
    "beneficiary": "Employees; employer implementation costs shown",
    "mode": "Team",
    "modeNote": "Team; Swarm for broad scenario analysis",
    "screen": "designer",
    "first": false
  },
  {
    "id": "G07",
    "category": "G",
    "categoryName": "Investment menu and portfolio improvement",
    "title": "Review currency risk and hedging costs",
    "work": "Compare available hedged and unhedged policies against retirement spending currency and risk capacity.",
    "measure": "Cost, return and downside trade-offs across FX scenarios.",
    "beneficiary": "Employees; employer implementation costs shown",
    "mode": "Team",
    "modeNote": "Team; Swarm for broad scenario analysis",
    "screen": "designer",
    "first": false
  },
  {
    "id": "G08",
    "category": "G",
    "categoryName": "Investment menu and portfolio improvement",
    "title": "Review bond duration and credit exposure",
    "work": "Assess policy-level rate sensitivity, credit concentration and liquidity against member needs.",
    "measure": "Risk exposures and eligible alternatives for consideration.",
    "beneficiary": "Employees; employer implementation costs shown",
    "mode": "Team",
    "modeNote": "Team; Swarm for broad scenario analysis",
    "screen": "designer",
    "first": false
  },
  {
    "id": "G09",
    "category": "G",
    "categoryName": "Investment menu and portfolio improvement",
    "title": "Optimize rebalancing within approved bands",
    "work": "Model policy rebalancing after transaction costs and dealing constraints; prepare authorized actions.",
    "measure": "Drift reduction and estimated implementation costs.",
    "beneficiary": "Employees; employer implementation costs shown",
    "mode": "Team",
    "modeNote": "Team; Swarm for broad scenario analysis",
    "screen": "designer",
    "first": false
  },
  {
    "id": "G10",
    "category": "G",
    "categoryName": "Investment menu and portfolio improvement",
    "title": "Stress-test the proposed portfolio",
    "work": "Run historical and forward scenarios with documented assumptions and uncertainty.",
    "measure": "Potential shortfall, loss ranges and probability estimates with model limits.",
    "beneficiary": "Employees; employer implementation costs shown",
    "mode": "Team",
    "modeNote": "Team; Swarm for broad scenario analysis",
    "screen": "designer",
    "first": false
  },
  {
    "id": "H01",
    "category": "H",
    "categoryName": "Personal employee returns and retirement planning",
    "title": "Build my retirement digital twin",
    "work": "Combine authorized account data, horizon, cash-flow needs and verified risk profile.",
    "measure": "Personal baseline with missing data and assumption ranges.",
    "beneficiary": "Employees; incremental employer matching disclosed",
    "mode": "Single",
    "modeNote": "Single for explanations; Team for recommendations",
    "screen": "employees",
    "first": false
  },
  {
    "id": "H02",
    "category": "H",
    "categoryName": "Personal employee returns and retirement planning",
    "title": "Calculate my actual personal return",
    "work": "Use cash-flow-aware calculations to separate investment performance from contributions and transfers.",
    "measure": "Personal money-weighted return and reconciled investment gain.",
    "beneficiary": "Employees; incremental employer matching disclosed",
    "mode": "Single",
    "modeNote": "Single for explanations; Team for recommendations",
    "screen": "employees",
    "first": false
  },
  {
    "id": "H03",
    "category": "H",
    "categoryName": "Personal employee returns and retirement planning",
    "title": "Review whether my current policy fits me",
    "work": "Compare the employee's selected policy with their horizon, risk capacity and available choices.",
    "measure": "Suitability review and explanations of possible alternatives.",
    "beneficiary": "Employees; incremental employer matching disclosed",
    "mode": "Single",
    "modeNote": "Single for explanations; Team for recommendations",
    "screen": "employees",
    "first": false
  },
  {
    "id": "H04",
    "category": "H",
    "categoryName": "Personal employee returns and retirement planning",
    "title": "Show what fees cost me over time",
    "work": "Calculate current fee drag and retirement projections using consistent return and contribution assumptions.",
    "measure": "Annual fee burden and projected long-term effect.",
    "beneficiary": "Employees; incremental employer matching disclosed",
    "mode": "Single",
    "modeNote": "Single for explanations; Team for recommendations",
    "screen": "employees",
    "first": true
  },
  {
    "id": "H05",
    "category": "H",
    "categoryName": "Personal employee returns and retirement planning",
    "title": "Compare my eligible alternatives fairly",
    "work": "Simulate current and alternative policies using identical cash flows and clearly stated risk differences.",
    "measure": "Net-wealth scenarios, ranges and switching costs.",
    "beneficiary": "Employees; incremental employer matching disclosed",
    "mode": "Single",
    "modeNote": "Single for explanations; Team for recommendations",
    "screen": "employees",
    "first": false
  },
  {
    "id": "H06",
    "category": "H",
    "categoryName": "Personal employee returns and retirement planning",
    "title": "Compare changing future contributions with switching existing assets",
    "work": "Assess directing new contributions differently versus reallocating the current balance, where permitted.",
    "measure": "Implementation costs, resulting exposures and transition time.",
    "beneficiary": "Employees; incremental employer matching disclosed",
    "mode": "Single",
    "modeNote": "Single for explanations; Team for recommendations",
    "screen": "employees",
    "first": false
  },
  {
    "id": "H07",
    "category": "H",
    "categoryName": "Personal employee returns and retirement planning",
    "title": "Find an affordable contribution level",
    "work": "Model employee cash-flow constraints, current rules and contribution choices.",
    "measure": "Retirement effect and take-home-pay trade-off; contribution gains separated from yield.",
    "beneficiary": "Employees; incremental employer matching disclosed",
    "mode": "Single",
    "modeNote": "Single for explanations; Team for recommendations",
    "screen": "employees",
    "first": false
  },
  {
    "id": "H08",
    "category": "H",
    "categoryName": "Personal employee returns and retirement planning",
    "title": "Check my available employer matching",
    "work": "Identify matching available under existing terms and the conditions to receive it.",
    "measure": "Potential additional contributions; incremental employer cost disclosed.",
    "beneficiary": "Employees; incremental employer matching disclosed",
    "mode": "Single",
    "modeNote": "Single for explanations; Team for recommendations",
    "screen": "employees",
    "first": false
  },
  {
    "id": "H09",
    "category": "H",
    "categoryName": "Personal employee returns and retirement planning",
    "title": "Measure my retirement shortfall in today's money",
    "work": "Model inflation, retirement age, income needs and assumptions with sensitivity ranges.",
    "measure": "Real retirement gap and possible actions.",
    "beneficiary": "Employees; incremental employer matching disclosed",
    "mode": "Single",
    "modeNote": "Single for explanations; Team for recommendations",
    "screen": "employees",
    "first": false
  },
  {
    "id": "H10",
    "category": "H",
    "categoryName": "Personal employee returns and retirement planning",
    "title": "Help me make disciplined investment decisions",
    "work": "Explain market movements and the consequences of panic selling or return-chasing using the member's circumstances.",
    "measure": "Informed choices; no claimed behavioral savings without supporting evidence.",
    "beneficiary": "Employees; incremental employer matching disclosed",
    "mode": "Single",
    "modeNote": "Single for explanations; Team for recommendations",
    "screen": "employees",
    "first": false
  },
  {
    "id": "I01",
    "category": "I",
    "categoryName": "Retirement transitions, tax and benefit protection",
    "title": "Plan risk reduction before retirement",
    "work": "Assess near-retirement losses and withdrawal timing against suitable available policies.",
    "measure": "Sequence-of-returns scenarios and a proposed transition plan.",
    "beneficiary": "Employees",
    "mode": "Team",
    "modeNote": "Team; qualified review for legal or tax conclusions",
    "screen": "employees",
    "first": false
  },
  {
    "id": "I02",
    "category": "I",
    "categoryName": "Retirement transitions, tax and benefit protection",
    "title": "Compare retirement dates",
    "work": "Model different retirement dates, contribution periods, benefit conditions and spending horizons.",
    "measure": "Net retirement resources and trade-offs under each scenario.",
    "beneficiary": "Employees",
    "mode": "Team",
    "modeNote": "Team; qualified review for legal or tax conclusions",
    "screen": "employees",
    "first": false
  },
  {
    "id": "I03",
    "category": "I",
    "categoryName": "Retirement transitions, tax and benefit protection",
    "title": "Compare options when changing employers",
    "work": "Evaluate eligible retention, transfer and withdrawal routes under current rules.",
    "measure": "Fees, tax implications, access restrictions and continuity of investment.",
    "beneficiary": "Employees",
    "mode": "Team",
    "modeNote": "Team; qualified review for legal or tax conclusions",
    "screen": "employees",
    "first": false
  },
  {
    "id": "I04",
    "category": "I",
    "categoryName": "Retirement transitions, tax and benefit protection",
    "title": "Calculate the consequences of early withdrawal",
    "work": "Compare immediate cash needs with potential tax effects and future compounding under explicit assumptions.",
    "measure": "After-tax cash today and modeled future wealth differences.",
    "beneficiary": "Employees",
    "mode": "Team",
    "modeNote": "Team; qualified review for legal or tax conclusions",
    "screen": "employees",
    "first": false
  },
  {
    "id": "I05",
    "category": "I",
    "categoryName": "Retirement transitions, tax and benefit protection",
    "title": "Compare eligible RMF-for-PVD transfer options",
    "work": "Where relevant, compare permitted receiving products, fees, risk, restrictions and services.",
    "measure": "Evidence-backed shortlist for review by the appropriate adviser.",
    "beneficiary": "Employees",
    "mode": "Team",
    "modeNote": "Team; qualified review for legal or tax conclusions",
    "screen": "employees",
    "first": false
  },
  {
    "id": "I06",
    "category": "I",
    "categoryName": "Retirement transitions, tax and benefit protection",
    "title": "Design a retirement withdrawal plan",
    "work": "Model eligible lump-sum or phased withdrawals, liquidity needs and investment risks.",
    "measure": "After-tax cash-flow scenarios and sustainability ranges.",
    "beneficiary": "Employees",
    "mode": "Team",
    "modeNote": "Team; qualified review for legal or tax conclusions",
    "screen": "employees",
    "first": false
  },
  {
    "id": "I07",
    "category": "I",
    "categoryName": "Retirement transitions, tax and benefit protection",
    "title": "Check contribution tax benefits",
    "work": "Apply verified current-year rules and other relevant retirement contributions to the individual's facts.",
    "measure": "Potential usable tax benefit, separate from investment return.",
    "beneficiary": "Employees",
    "mode": "Team",
    "modeNote": "Team; qualified review for legal or tax conclusions",
    "screen": "employees",
    "first": false
  },
  {
    "id": "I08",
    "category": "I",
    "categoryName": "Retirement transitions, tax and benefit protection",
    "title": "Reconcile tax and benefit documents",
    "work": "Cross-check contribution certificates, statements and relevant tax inputs; identify missing or inconsistent records.",
    "measure": "Supported corrections and avoided duplicate claims.",
    "beneficiary": "Employees",
    "mode": "Team",
    "modeNote": "Team; qualified review for legal or tax conclusions",
    "screen": "employees",
    "first": false
  },
  {
    "id": "I09",
    "category": "I",
    "categoryName": "Retirement transitions, tax and benefit protection",
    "title": "Protect beneficiary and dormant-account entitlements",
    "work": "Review authorized beneficiary records and unresolved balances; prepare documented follow-up.",
    "measure": "Valid records and rightful benefits located or claimed.",
    "beneficiary": "Employees",
    "mode": "Team",
    "modeNote": "Team; qualified review for legal or tax conclusions",
    "screen": "employees",
    "first": false
  },
  {
    "id": "I10",
    "category": "I",
    "categoryName": "Retirement transitions, tax and benefit protection",
    "title": "Verify vesting and benefit allocations",
    "work": "Recalculate employee entitlements under existing applicable terms and investigate discrepancies.",
    "measure": "Amounts correctly attributed and evidence for rectification.",
    "beneficiary": "Employees",
    "mode": "Team",
    "modeNote": "Team; qualified review for legal or tax conclusions",
    "screen": "employees",
    "first": false
  },
  {
    "id": "J01",
    "category": "J",
    "categoryName": "Plan design that improves employee value",
    "title": "Improve employee outcomes within a fixed employer budget",
    "work": "Compare lower fees, better services and suitable policies while preserving existing promised benefits.",
    "measure": "Feasible designs and employee outcome ranges at the stated budget.",
    "beneficiary": "Employer and employees",
    "mode": "Team",
    "modeNote": "Team; Swarm for workforce simulations",
    "screen": "designer",
    "first": false
  },
  {
    "id": "J02",
    "category": "J",
    "categoryName": "Plan design that improves employee value",
    "title": "Model reinvestment of verified savings",
    "work": "Compare retaining employer cash savings with voluntarily using part to improve member services or contributions.",
    "measure": "Employer retained savings and additional employee value shown separately.",
    "beneficiary": "Employer and employees",
    "mode": "Team",
    "modeNote": "Team; Swarm for workforce simulations",
    "screen": "designer",
    "first": false
  },
  {
    "id": "J03",
    "category": "J",
    "categoryName": "Plan design that improves employee value",
    "title": "Evaluate matching-design alternatives",
    "work": "Model legally feasible prospective designs with explicit treatment of existing rights and incremental costs.",
    "measure": "Marginal employer cost per improvement in retirement outcomes.",
    "beneficiary": "Employer and employees",
    "mode": "Team",
    "modeNote": "Team; Swarm for workforce simulations",
    "screen": "designer",
    "first": false
  },
  {
    "id": "J04",
    "category": "J",
    "categoryName": "Plan design that improves employee value",
    "title": "Build the case for more employee investment choice",
    "work": "Evaluate additional eligible policies against member needs, administrative complexity and cost.",
    "measure": "Menu-expansion business case and provider requirements.",
    "beneficiary": "Employer and employees",
    "mode": "Team",
    "modeNote": "Team; Swarm for workforce simulations",
    "screen": "designer",
    "first": false
  },
  {
    "id": "J05",
    "category": "J",
    "categoryName": "Plan design that improves employee value",
    "title": "Plan life-path adoption",
    "work": "Model appropriate member cohorts, provider options, communication and applicable consent requirements.",
    "measure": "Expected reach, implementation cost and outcome scenarios.",
    "beneficiary": "Employer and employees",
    "mode": "Team",
    "modeNote": "Team; Swarm for workforce simulations",
    "screen": "designer",
    "first": false
  },
  {
    "id": "J06",
    "category": "J",
    "categoryName": "Plan design that improves employee value",
    "title": "Target retirement support where it helps most",
    "work": "Use privacy-protecting cohort analysis to identify gaps and test suitable interventions.",
    "measure": "Intervention cost and change in modeled retirement adequacy.",
    "beneficiary": "Employer and employees",
    "mode": "Team",
    "modeNote": "Team; Swarm for workforce simulations",
    "screen": "designer",
    "first": false
  },
  {
    "id": "J07",
    "category": "J",
    "categoryName": "Plan design that improves employee value",
    "title": "Design voluntary contribution escalation",
    "work": "Assess opt-in increases against affordability, permitted rules and any employer-match effects.",
    "measure": "Employee take-home-pay impact and incremental contributions.",
    "beneficiary": "Employer and employees",
    "mode": "Team",
    "modeNote": "Team; Swarm for workforce simulations",
    "screen": "designer",
    "first": false
  },
  {
    "id": "J08",
    "category": "J",
    "categoryName": "Plan design that improves employee value",
    "title": "Create personalized financial education",
    "work": "Generate grounded multilingual explanations and check understanding of risk, fees and choices.",
    "measure": "Comprehension and informed-action metrics.",
    "beneficiary": "Employer and employees",
    "mode": "Team",
    "modeNote": "Team; Swarm for workforce simulations",
    "screen": "designer",
    "first": false
  },
  {
    "id": "J09",
    "category": "J",
    "categoryName": "Plan design that improves employee value",
    "title": "Improve participation with transparent costs",
    "work": "Analyze enrollment barriers and propose accessible communication or process changes.",
    "measure": "Participation scenarios and full incremental employer funding cost.",
    "beneficiary": "Employer and employees",
    "mode": "Team",
    "modeNote": "Team; Swarm for workforce simulations",
    "screen": "designer",
    "first": false
  },
  {
    "id": "J10",
    "category": "J",
    "categoryName": "Plan design that improves employee value",
    "title": "Check who benefits or loses from a redesign",
    "work": "Compare cohort impacts, fee incidence, existing rights and service access before any change.",
    "measure": "Distributional impact report and revisions for unfair outcomes.",
    "beneficiary": "Employer and employees",
    "mode": "Team",
    "modeNote": "Team; Swarm for workforce simulations",
    "screen": "designer",
    "first": false
  },
  {
    "id": "K01",
    "category": "K",
    "categoryName": "Continuous monitoring and new mission generation",
    "title": "Watch for fee increases and expired discounts",
    "work": "Monitor verified fee schedules, invoices, waivers and actual charges.",
    "measure": "Change alerts with beneficiary-specific annualized exposure.",
    "beneficiary": "Employer and employees",
    "mode": "Single",
    "modeNote": "Single monitors; Team investigations",
    "screen": "watch",
    "first": false
  },
  {
    "id": "K02",
    "category": "K",
    "categoryName": "Continuous monitoring and new mission generation",
    "title": "Watch for new pricing-tier eligibility",
    "work": "Track assets and member counts against contractual or quoted thresholds.",
    "measure": "Actionable repricing opportunities.",
    "beneficiary": "Employer and employees",
    "mode": "Single",
    "modeNote": "Single monitors; Team investigations",
    "screen": "watch",
    "first": false
  },
  {
    "id": "K03",
    "category": "K",
    "categoryName": "Continuous monitoring and new mission generation",
    "title": "Watch for meaningful performance deterioration",
    "work": "Apply pre-agreed comparable benchmarks, periods and statistical checks.",
    "measure": "Evidence-based investigation triggers.",
    "beneficiary": "Employer and employees",
    "mode": "Single",
    "modeNote": "Single monitors; Team investigations",
    "screen": "watch",
    "first": false
  },
  {
    "id": "K04",
    "category": "K",
    "categoryName": "Continuous monitoring and new mission generation",
    "title": "Watch for excessive risk or portfolio drift",
    "work": "Monitor available exposure, concentration, drawdown and mandate information.",
    "measure": "Risk exceptions requiring review.",
    "beneficiary": "Employer and employees",
    "mode": "Single",
    "modeNote": "Single monitors; Team investigations",
    "screen": "watch",
    "first": false
  },
  {
    "id": "K05",
    "category": "K",
    "categoryName": "Continuous monitoring and new mission generation",
    "title": "Watch provider operational and team changes",
    "work": "Track verified service deterioration, personnel changes and other material provider events.",
    "measure": "Impact assessment and due-diligence follow-up.",
    "beneficiary": "Employer and employees",
    "mode": "Single",
    "modeNote": "Single monitors; Team investigations",
    "screen": "watch",
    "first": false
  },
  {
    "id": "K06",
    "category": "K",
    "categoryName": "Continuous monitoring and new mission generation",
    "title": "Detect stale, missing or inconsistent data",
    "work": "Check source freshness, completeness and reconciliation; suspend unsupported rankings.",
    "measure": "Data-remediation tasks and visible confidence flags.",
    "beneficiary": "Employer and employees",
    "mode": "Single",
    "modeNote": "Single monitors; Team investigations",
    "screen": "watch",
    "first": false
  },
  {
    "id": "K07",
    "category": "K",
    "categoryName": "Continuous monitoring and new mission generation",
    "title": "Watch renewal and switching opportunities",
    "work": "Monitor contractual deadlines, notice windows and eligibility for competing offers.",
    "measure": "Timely review or tender tasks before options expire.",
    "beneficiary": "Employer and employees",
    "mode": "Single",
    "modeNote": "Single monitors; Team investigations",
    "screen": "watch",
    "first": false
  },
  {
    "id": "K08",
    "category": "K",
    "categoryName": "Continuous monitoring and new mission generation",
    "title": "Watch contribution and allocation delays",
    "work": "Continuously reconcile remittances and postings; investigate overdue exceptions.",
    "measure": "Unallocated amounts, duration and resolution ownership.",
    "beneficiary": "Employer and employees",
    "mode": "Single",
    "modeNote": "Single monitors; Team investigations",
    "screen": "watch",
    "first": false
  },
  {
    "id": "K09",
    "category": "K",
    "categoryName": "Continuous monitoring and new mission generation",
    "title": "Update missions when applicable rules change",
    "work": "Track authoritative publications, proposal versus effective status and affected contracts or members.",
    "measure": "Versioned impact assessment and required re-review tasks.",
    "beneficiary": "Employer and employees",
    "mode": "Single",
    "modeNote": "Single monitors; Team investigations",
    "screen": "watch",
    "first": false
  },
  {
    "id": "K10",
    "category": "K",
    "categoryName": "Continuous monitoring and new mission generation",
    "title": "Generate the next best action plan",
    "work": "Turn validated alerts into ranked missions using value, urgency, confidence, cost and permissions.",
    "measure": "Recommended mission queue with an execution budget.",
    "beneficiary": "Employer and employees",
    "mode": "Single",
    "modeNote": "Single monitors; Team investigations",
    "screen": "watch",
    "first": false
  },
  {
    "id": "L01",
    "category": "L",
    "categoryName": "Proof of value, governance and accumulated intelligence",
    "title": "Freeze the baseline before acting",
    "work": "Record source versions, dates, asset bases, service levels, risk assumptions and the chosen comparison.",
    "measure": "Reproducible baseline and benefit measurement plan.",
    "beneficiary": "Employer and employees",
    "mode": "Team",
    "modeNote": "Team with an independent challenger",
    "screen": "outcome",
    "first": false
  },
  {
    "id": "L02",
    "category": "L",
    "categoryName": "Proof of value, governance and accumulated intelligence",
    "title": "Verify employer net savings",
    "work": "Reconcile actual avoided invoices, realized refunds and cash costs; subtract platform, AI and implementation expenses.",
    "measure": "Evidence-backed recurring and first-year net cash benefit; capacity gains separate.",
    "beneficiary": "Employer and employees",
    "mode": "Team",
    "modeNote": "Team with an independent challenger",
    "screen": "outcome",
    "first": true
  },
  {
    "id": "L03",
    "category": "L",
    "categoryName": "Proof of value, governance and accumulated intelligence",
    "title": "Verify employee fee savings",
    "work": "Recalculate costs on a common asset and exposure basis; separate fee-rate changes from NAV and membership changes.",
    "measure": "Fund/member fee reductions credited to the correct beneficiaries.",
    "beneficiary": "Employer and employees",
    "mode": "Team",
    "modeNote": "Team with an independent challenger",
    "screen": "outcome",
    "first": true
  },
  {
    "id": "L04",
    "category": "L",
    "categoryName": "Proof of value, governance and accumulated intelligence",
    "title": "Evaluate investment outcomes against the agreed alternative",
    "work": "Track actual and counterfactual net returns using matched cash flows, risk disclosure and prespecified methods.",
    "measure": "Observed relative outcome with uncertainty; no automatic causal claim.",
    "beneficiary": "Employer and employees",
    "mode": "Team",
    "modeNote": "Team with an independent challenger",
    "screen": "outcome",
    "first": false
  },
  {
    "id": "L05",
    "category": "L",
    "categoryName": "Proof of value, governance and accumulated intelligence",
    "title": "Explain changes in employee wealth",
    "work": "Attribute changes to contributions, matching, fees, markets, allocation, transfers and tax effects without overlaps.",
    "measure": "Clear wealth bridge and separate benefit categories.",
    "beneficiary": "Employer and employees",
    "mode": "Team",
    "modeNote": "Team with an independent challenger",
    "screen": "outcome",
    "first": false
  },
  {
    "id": "L06",
    "category": "L",
    "categoryName": "Proof of value, governance and accumulated intelligence",
    "title": "Independently challenge every material recommendation",
    "work": "Use separate review of evidence, calculations, assumptions, cherry-picking and conflicts.",
    "measure": "Resolved objections and remaining uncertainty before approval.",
    "beneficiary": "Employer and employees",
    "mode": "Team",
    "modeNote": "Team with an independent challenger",
    "screen": "outcome",
    "first": false
  },
  {
    "id": "L07",
    "category": "L",
    "categoryName": "Proof of value, governance and accumulated intelligence",
    "title": "Prepare and preserve committee decisions",
    "work": "Draft evidence-linked agendas, papers, minutes, approvals and action follow-ups.",
    "measure": "Less administrative work and traceable decision history.",
    "beneficiary": "Employer and employees",
    "mode": "Team",
    "modeNote": "Team with an independent challenger",
    "screen": "outcome",
    "first": false
  },
  {
    "id": "L08",
    "category": "L",
    "categoryName": "Proof of value, governance and accumulated intelligence",
    "title": "Score providers on delivered outcomes",
    "work": "Compare quoted fees, migration promises, service levels and documented results with actual delivery.",
    "measure": "Private verified scorecards; permitted aggregation only.",
    "beneficiary": "Employer and employees",
    "mode": "Team",
    "modeNote": "Team with an independent challenger",
    "screen": "outcome",
    "first": false
  },
  {
    "id": "L09",
    "category": "L",
    "categoryName": "Proof of value, governance and accumulated intelligence",
    "title": "Improve anonymized market benchmarks",
    "work": "With appropriate rights and safeguards, incorporate realized fees, service scope and outcomes into comparable cohorts.",
    "measure": "Stronger benchmarks with sample-size, freshness and privacy controls.",
    "beneficiary": "Employer and employees",
    "mode": "Team",
    "modeNote": "Team with an independent challenger",
    "screen": "outcome",
    "first": false
  },
  {
    "id": "L10",
    "category": "L",
    "categoryName": "Proof of value, governance and accumulated intelligence",
    "title": "Learn which missions deliver useful results",
    "work": "Analyze completed missions, data quality, acceptance, costs and verified outcomes; recalibrate ranking rules.",
    "measure": "Better future prioritization supported by measured evidence.",
    "beneficiary": "Employer and employees",
    "mode": "Team",
    "modeNote": "Team with an independent challenger",
    "screen": "outcome",
    "first": false
  }
];

export const ENTRY_MISSIONS: { id: string; title: string; request: string; ids: string[]; deliverable: string }[] = [
  {
    "id": "save-my-company-money",
    "title": "Save my company money",
    "request": "Find achievable savings while preserving employee benefits and service standards.",
    "ids": [
      "A01",
      "A02",
      "A03",
      "A04",
      "A05",
      "A06",
      "A07",
      "A08",
      "A09",
      "A10",
      "B01",
      "B02",
      "B03",
      "B04",
      "B05",
      "B06",
      "B07",
      "B08",
      "B09",
      "B10",
      "E10",
      "L01",
      "L02"
    ],
    "deliverable": "Prioritized net employer savings plan"
  },
  {
    "id": "keep-more-in-employee-funds",
    "title": "Keep more in employee funds",
    "request": "Identify and reduce the fees employees actually bear.",
    "ids": [
      "A01",
      "A02",
      "A03",
      "A04",
      "A05",
      "A06",
      "A07",
      "A08",
      "B01",
      "B02",
      "C05",
      "H04",
      "L03"
    ],
    "deliverable": "Member/fund fee savings with beneficiaries identified"
  },
  {
    "id": "improve-investment-outcomes",
    "title": "Improve investment outcomes",
    "request": "Assess eligible alternatives after fees at appropriate risk.",
    "ids": [
      "F01",
      "F02",
      "F03",
      "F04",
      "F05",
      "F06",
      "F07",
      "F08",
      "F09",
      "F10",
      "G01",
      "G02",
      "G03",
      "G04",
      "G05",
      "G06",
      "G07",
      "G08",
      "G09",
      "G10",
      "H03",
      "H04",
      "H05",
      "L04"
    ],
    "deliverable": "Evidence-backed comparisons and uncertain future scenarios"
  },
  {
    "id": "run-a-competitive-tender",
    "title": "Run a competitive tender",
    "request": "Help qualified providers compete on price, investment quality and service.",
    "ids": [
      "C01",
      "C02",
      "C03",
      "C04",
      "C05",
      "C06",
      "C07",
      "C08",
      "C09",
      "C10",
      "B06",
      "L06",
      "L07"
    ],
    "deliverable": "Comparable final offers and committee decision pack"
  },
  {
    "id": "decide-whether-to-switch",
    "title": "Decide whether to switch",
    "request": "Compare keeping, renegotiating and moving the fund.",
    "ids": [
      "D01",
      "D02",
      "D03",
      "D04",
      "D05",
      "D06",
      "D07",
      "D08",
      "D09",
      "D10",
      "L01",
      "L02",
      "L03",
      "L04"
    ],
    "deliverable": "Payback, transition plan and post-implementation evidence"
  },
  {
    "id": "prove-epf24-s-value",
    "title": "Prove EPF24's value",
    "request": "Show the financial results attributable to completed actions and the limits of attribution.",
    "ids": [
      "L01",
      "L02",
      "L03",
      "L04",
      "L05",
      "L06",
      "L07",
      "L08",
      "L09",
      "L10"
    ],
    "deliverable": "Employer cash results, employee fee savings and separate investment analysis"
  }
];
