import type { ScreenId } from "@/lib/model";

export type Guide = {
  code: string;
  name: string;
  summary: string;
  when: string;
  need: string;
  leave: string;
  features: { title: string; body: string }[];
  before: string;
  steps: { title: string; body: string }[];
  outcome: string;
  related: { id: ScreenId; label: string }[];
};

function g(guide: Guide) {
  return guide;
}

const HOME = g({
  code: "01",
  name: "Dashboard",
  summary: "See whether this provident fund is still competitive, and split the employer’s fee gap from the members’ wealth scenario.",
  when: "Open the dashboard at the start of a review, before a committee meeting, or when someone asks what the fund is worth changing.",
  need: "The open employer file: assets, headcount, the current provider, and the sample-book fee and return assumptions. Advisor mode reads this as a client mandate. Corporate mode reads it as the company’s own fund.",
  leave: "One annual figure, labeled as a scenario, plus the next question to open: benchmark, value gap, workforce, or a market test. Leaving the current arrangement in place is a valid result.",
  features: [
    { title: "Annual value gap", body: "The headline baht figure. Corporate fee opportunity and employee wealth opportunity stay on separate lines and are not added into a guaranteed saving." },
    { title: "EPF health", body: "A short read of fee, return, participation and service against the sample book, so the meeting starts from the fund rather than from a single alert." },
    { title: "AI insights", body: "Sentences that explain the calculated figures. The engines produce the numbers. The text does not replace them." },
    { title: "Active alerts", body: "Items that have crossed a threshold the committee already set. A quiet list means nothing has crossed the line." },
    { title: "Committee actions", body: "Open work attached to people and dates. Nothing here is sent to a provider by itself." },
    { title: "Four questions", body: "Performance, fee, employee outcomes, and whether to test the market. Each one opens the page that can answer it." },
  ],
  before: "Confirm which employer file is open, and whether you are in advisor mode or corporate mode. The numbers are the Rattana sample book until a contract file replaces them.",
  steps: [
    { title: "Read the two lines under the annual figure", body: "Keep the employer fee difference apart from the member wealth scenario. Do not quote them as one promised saving." },
    { title: "Open the question that matters", body: "Benchmark for performance, Value Gap for the committee number, Workforce for outcomes, or Market Test before any promise to move." },
    { title: "Check the source of each figure", body: "A contract fee, a published SEC fee, and an EPF24 calculation are different lanes. Say which one you are using." },
    { title: "Choose a next step, including no action", body: "Renegotiate, test the market, or record that the current arrangement is still competitive." },
  ],
  outcome: "A labeled scenario for this fund, and one next page, ready for the committee. No letter has been sent.",
  related: [
    { id: "gap", label: "Value Gap" },
    { id: "bench", label: "Benchmark" },
    { id: "market", label: "Market Test" },
    { id: "workforce", label: "Retirement Intelligence" },
  ],
});

const GUIDES: { title: string; guide: Guide }[] = [
  { title: "Pay less. Earn more.", guide: g({
    code: "02",
    name: "My PVD",
    summary: "Show the employer’s negotiated fee gap and the members’ investment scenario as two results, not one promise.",
    when: "Use My PVD when the employer wants the plain version of the fund: what it costs, and what a different return path would mean for members.",
    need: "The negotiated fee on the open file, assets, and the stated return assumptions. A published factsheet fee is not this page.",
    leave: "Two numbers the employer can repeat: the annual fee difference, and the member wealth scenario, each with its own label.",
    features: [
      { title: "Employer fee gap", body: "The difference between the current negotiated cost and the best-fit cost in the sample book. It is a fee comparison, not a completed switch." },
      { title: "Member wealth scenario", body: "Compound math on the stated returns over the chosen horizon. It is not a forecast and not a fee." },
      { title: "Source split", body: "The page keeps the contract lane and the investment scenario apart so they are not added into one guaranteed result." },
      { title: "Next pages", body: "Fee X-Ray for the contract lines. Value Gap for the committee number. Scenario lab to move one assumption." },
    ],
    before: "Have the current all-in fee and the asset balance. Do not paste a factsheet fee into the negotiated line.",
    steps: [
      { title: "Read the employer number first", body: "Confirm it is the negotiated cost, not a published fund fee." },
      { title: "Read the member number second", body: "Treat it as a scenario on the stated returns. Do not add it to the fee gap." },
      { title: "Open the contract if the fee is questioned", body: "Fee X-Ray shows the lines and the clauses. This page only shows the result." },
      { title: "Decide whether a market test is warranted", body: "A gap is a reason to test or renegotiate. It is not itself a decision to move." },
    ],
    outcome: "A two-line brief the employer can take into a meeting, with the fee and the wealth scenario still separate.",
    related: [
      { id: "xray", label: "Fee X-Ray" },
      { id: "gap", label: "Value Gap" },
      { id: "lab", label: "Scenario lab" },
    ],
  }) },
  { title: "Every baht in the contract, with its clause.", guide: g({
    code: "03",
    name: "Fee X-Ray",
    summary: "Read every line of the negotiated fee schedule against its clause, and keep the published market fee in a different lane.",
    when: "Use Fee X-Ray when someone asks what the employer actually pays, or when a factsheet price is being mistaken for the contract.",
    need: "The uploaded fee schedule. A reviewed contract is the source. A public factsheet is context only.",
    leave: "A line-by-line total of the negotiated corporate fee, with the published lane shown beside it and not inside the total.",
    features: [
      { title: "Negotiated corporate fee", body: "The lines extracted from the employer’s file. The total is the contract, not the market." },
      { title: "Clause reference", body: "Each line stays attached to the clause it came from, so a meeting can point at the document." },
      { title: "Published market lane", body: "What a factsheet might show. It is displayed apart and is not added into the negotiated total." },
      { title: "Handoff", body: "The reviewed total is what My PVD, Value Gap and the committee pack should use." },
    ],
    before: "The fee schedule should be marked reviewed in Documents. An extracting file is not ready to quote.",
    steps: [
      { title: "Start from the uploaded schedule", body: "Ignore the factsheet until the contract lines are read." },
      { title: "Check each line against its clause", body: "If a line has no clause, do not treat it as agreed." },
      { title: "Leave the published fee outside the total", body: "Show it as a comparison. Do not blend it into the negotiated cost." },
      { title: "Carry the total forward", body: "Use this total on My PVD and in the committee pack. Do not retype a different number." },
    ],
    outcome: "A contract fee the committee can defend, with the published fee still visibly separate.",
    related: [
      { id: "docs", label: "Documents" },
      { id: "mypvd", label: "My PVD" },
      { id: "gap", label: "Value Gap" },
    ],
  }) },
  { title: "How much value is the current fund leaving on the table?", guide: g({
    code: "04",
    name: "Value Gap",
    summary: "Give the CEO, CFO, CHRO and the committee one annual figure, built from fee, performance, risk, service, choice and participation.",
    when: "Use Value Gap when the meeting needs a single number and the drivers behind it, not a stack of alerts.",
    need: "The open employer file and the sample-book comparison. Say that the figure is a scenario before it leaves the room.",
    leave: "The annual gap, the efficiency meter, and a what-if that shows fee saving and member wealth separately.",
    features: [
      { title: "One annual number", body: "The figure for the meeting. It is the sum of a fee opportunity and an investment scenario, and both stay visible." },
      { title: "Value meter", body: "How close the current arrangement sits to the comparison set. It is not a credit rating." },
      { title: "Drivers", body: "Fee, performance, risk, service, choice, retirement and participation. The gap has a cause, not only a total." },
      { title: "What if we change", body: "Renegotiate, take the best fit, or take the cheapest. Cheapest is shown so it can be rejected." },
    ],
    before: "Agree which comparison is in use. The Rattana book is a scenario, not a live bid.",
    steps: [
      { title: "Read the annual figure with its two parts", body: "Quote the fee line and the wealth line, not only the total." },
      { title: "Name the drivers", body: "If the gap is mostly fee, do not describe it as a performance failure, and the reverse." },
      { title: "Look at the what-if paths", body: "Include the path that stays with the incumbent at a better price." },
      { title: "Take one next action", body: "A market test, a reprice, or no action. The page does not award a mandate." },
    ],
    outcome: "A committee-ready number with its drivers, still labeled as a scenario.",
    related: [
      { id: "home", label: "Dashboard" },
      { id: "market", label: "Market Test" },
      { id: "bench", label: "Benchmark" },
    ],
  }) },
  { title: "Your EPF versus the relevant market.", guide: g({
    code: "05",
    name: "Benchmark",
    summary: "Place this fund against comparable employers on fee, return, risk and service, after the agreement and factsheets are in the file.",
    when: "Use Benchmark when the question is “are we in range,” not “who should we hire.”",
    need: "The agreement, factsheets and fee schedule. Until those are loaded, the screen is the Rattana sample scenario.",
    leave: "A peer comparison the committee can accept or challenge, plus one action that follows from the gap.",
    features: [
      { title: "Current EPF X-Ray", body: "The fund as extracted: fee, policy, service and the terms that matter for a comparison." },
      { title: "Peer placement", body: "The fund against comparable employers, not against a single advertised return." },
      { title: "AI action", body: "The suggested next step. It can be to hold, renegotiate, or test. It is not an instruction already sent." },
      { title: "Source check", body: "Uploaded documents outrank the sample book. If the file is empty, say the figure is still the sample." },
    ],
    before: "Load the agreement and the fee schedule from Documents, or accept that you are still on the sample scenario.",
    steps: [
      { title: "Confirm the file is loaded", body: "An empty upload means the comparison is illustrative." },
      { title: "Read the fund against the peer set", body: "Do not judge the fund from one year or one policy in isolation." },
      { title: "Separate a fee gap from a return gap", body: "Take each gap to the page that can act on it." },
      { title: "Write the action in the committee record", body: "Benchmark proposes. The committee decides." },
    ],
    outcome: "A sourced comparison and one proposed action, ready to minute.",
    related: [
      { id: "docs", label: "Documents" },
      { id: "gap", label: "Value Gap" },
      { id: "compare", label: "Provider comparison" },
    ],
  }) },
  { title: "Continuous monitoring. Exceptions only.", guide: g({
    code: "06",
    name: "EPF Watch",
    summary: "Watch performance, risk, fee, service, outcomes and governance, and surface only what crossed a threshold the committee set.",
    when: "Use Watch between meetings, when the question is whether anything has changed enough to deserve attention.",
    need: "The thresholds already agreed, and the current fund record. Do not invent a new hurdle on this page.",
    leave: "An exception list with owners, or a clear statement that nothing crossed the line.",
    features: [
      { title: "Exception alerts", body: "Only the breaches. The page is not a second dashboard of everything that is fine." },
      { title: "Peer excess return", body: "The balanced policy against the peer median, so a bad month can be seen without a new recommendation." },
      { title: "Thresholds", body: "The limits live in Admin. Watch applies them. It does not rewrite them." },
      { title: "No automatic switch", body: "An alert is a reason to look. It is not a decision to change provider." },
    ],
    before: "Confirm the monitoring thresholds in Admin before treating an alert as agreed policy.",
    steps: [
      { title: "Read only the breached rows", body: "Ignore the measures that are inside the band." },
      { title: "Name the threshold that failed", body: "An alert without its rule is not ready for the committee." },
      { title: "Assign an owner and a date", body: "Attach the item to a person. Do not leave it as a banner." },
      { title: "Escalate only if the rule says so", body: "A quiet page is a result. Record that nothing crossed the line." },
    ],
    outcome: "Either an owned exception or a recorded all-clear. No provider has been contacted.",
    related: [
      { id: "committee", label: "Committee AI" },
      { id: "settings", label: "Admin" },
      { id: "bench", label: "Benchmark" },
    ],
  }) },
  { title: "Secretary, analyst and memory for the committee.", guide: g({
    code: "07",
    name: "Committee AI",
    summary: "Prepare the meeting from the fund record, and keep decisions and actions attached to the meeting that made them.",
    when: "Use Committee AI before the sitting, and again when the minutes and the actions need a home.",
    need: "The fund record, the open alerts, and the questions for the current provider. A person still releases anything that leaves the room.",
    leave: "A pack, a decision, and named actions. Nothing is sent to the provider until the secretary releases it.",
    features: [
      { title: "Executive summary", body: "The meeting in one read, drawn from the same figures as the dashboard." },
      { title: "Agenda", body: "The items the committee will actually decide, not a tour of every screen." },
      { title: "Questions for the provider", body: "What to ask the incumbent. Drafted here, sent only after release." },
      { title: "Detected items", body: "What the record already shows, so the meeting does not rediscover it." },
      { title: "Decisions and actions", body: "Kept on this meeting. Later packs can see what was agreed." },
    ],
    before: "The fee total and the value gap should already be the numbers you are willing to say aloud.",
    steps: [
      { title: "Review the drafted pack against the fund record", body: "Correct a sentence that does not match Fee X-Ray or Value Gap." },
      { title: "Edit the decision in the meeting", body: "Do not keep the real decision in a side note." },
      { title: "Name each action", body: "Owner and date. An unowned action is not an action." },
      { title: "Release nothing until sign-out", body: "A draft question is not a letter to the provider." },
    ],
    outcome: "Minutes and actions attached to this meeting, with outbound messages still unsent.",
    related: [
      { id: "reports", label: "Reports" },
      { id: "watch", label: "EPF Watch" },
      { id: "docs", label: "Documents" },
    ],
  }) },
  { title: "Reports for the CFO, the board and the committee.", guide: g({
    code: "08",
    name: "Reports",
    summary: "Restate the same scenario for the CFO, the board and the committee, without creating a new set of numbers.",
    when: "Use Reports when a reader needs the fund in their own format, after the dashboard figures are settled.",
    need: "The current scenario. Generating a report does not recalculate the fund.",
    leave: "A report whose fee opportunity and member wealth still match the dashboard, labeled for that reader.",
    features: [
      { title: "Reader choice", body: "CFO, board, or committee. The facts stay the same. The emphasis changes." },
      { title: "Generate", body: "Builds the report from the existing scenario. It does not fetch a new market price." },
      { title: "Number lock", body: "The baht figures are the ones already on the dashboard. If they disagree, fix the source, not the prose." },
      { title: "Label", body: "Fee and wealth remain separate sentences so a board pack cannot collapse them into a guarantee." },
    ],
    before: "Settle Value Gap and Fee X-Ray first. A report written before that will repeat the wrong number cleanly.",
    steps: [
      { title: "Pick the reader", body: "Do not write three different totals for three readers." },
      { title: "Generate from the dashboard scenario", body: "If a figure looks new, stop and check the source page." },
      { title: "Check the two labels", body: "Employer fee opportunity and member wealth scenario must both appear." },
      { title: "File it on the meeting", body: "A generated report still needs the committee record if it will be used." },
    ],
    outcome: "A reader-specific report that quotes the same scenario the committee already has.",
    related: [
      { id: "home", label: "Dashboard" },
      { id: "gap", label: "Value Gap" },
      { id: "committee", label: "Committee AI" },
    ],
  }) },
  { title: "Provident-fund companies and pooled products.", guide: g({
    code: "09",
    name: "PVD Market",
    summary: "See the companies licensed to provide provident-fund services, and the pooled product names, without mixing in employer funds.",
    when: "Use PVD Market when the question is who is licensed, or what a pooled product is called. Employer funds live on Employers.",
    need: "Nothing from the employer’s contract. This list is the register, in English. Search still matches the Thai source name.",
    leave: "A company or a product name you can take back to the mandate. Not a return, a fee, or a ranking.",
    features: [
      { title: "Company cards", body: "The licensed managers. Life Path and RMF tags describe the company, not a performance." },
      { title: "Pooled products", body: "Product names from the register. They are not the employer’s bespoke fund." },
      { title: "English list", body: "The visible name is English. The Thai register string remains searchable." },
      { title: "No invented returns", body: "A real fund name on this page is not given a made-up performance." },
    ],
    before: "Decide whether you are looking for a company, a pooled product, or an employer. The third belongs on Employers.",
    steps: [
      { title: "Scan the company cards", body: "Note Life Path and RMF only as capabilities." },
      { title: "Use the product table for product names", body: "Do not treat a pooled nickname as the employer’s fund." },
      { title: "Open Employers for a company fund", body: "Master funds that belong to one employer are not products." },
      { title: "Bring the name back, not a score", body: "This page does not rank providers." },
    ],
    outcome: "The right name, in the right list, with no performance attached.",
    related: [
      { id: "employers", label: "Employers" },
      { id: "compare", label: "Provider comparison" },
      { id: "gateway", label: "Public data" },
    ],
  }) },
  { title: "Employers with a registered provident fund.", guide: g({
    code: "10",
    name: "Employers",
    summary: "Find an employer fund on the register, in English, without treating the row as a bid or a recommendation.",
    when: "Use Employers when you need the fund’s name as it sits on the Thai register, separate from the company cards.",
    need: "A name, in English or Thai. The list does not contain fees or returns.",
    leave: "A confirmed employer-fund name to attach to the open mandate.",
    features: [
      { title: "English names", body: "Each row is the English form of a register entry. The Thai string is kept for search." },
      { title: "Employer, not product", body: "Pooled products stay on PVD Market. This list is the employer funds." },
      { title: "No price", body: "A row is not a quotation and not a reason to switch." },
      { title: "Traceability", body: "You can find the original register name even though the table shows English." },
    ],
    before: "Have the name you were given, including the Thai spelling if the English search misses.",
    steps: [
      { title: "Search English first", body: "If it misses, paste the Thai register name." },
      { title: "Confirm it is an employer fund", body: "If it is a pooled product, go back to PVD Market." },
      { title: "Attach it to the open mandate", body: "The name identifies the fund. It does not price it." },
      { title: "Stop before inventing a fee", body: "Fees come from the contract or from SEC data, not from this list." },
    ],
    outcome: "The employer fund identified, and nothing else claimed about it.",
    related: [
      { id: "intel", label: "PVD Market" },
      { id: "network", label: "Intelligence network" },
    ],
  }) },
  { title: "The SEC provident-fund API is the market feed. The page does not call it.", guide: g({
    code: "11",
    name: "Intelligence network",
    summary: "See how SEC Open Data is synced into EPF24, and which scores are calculated here rather than published by the SEC.",
    when: "Use the intelligence network when someone asks where a market figure came from, or whether the page is calling the SEC.",
    need: "The connector status. Pages do not call the SEC. A subscription key and pinned paths are required before a sync runs.",
    leave: "A clear line between SEC-reported data, EPF24 calculations on the sample book, and the employer’s private contract.",
    features: [
      { title: "SEC connector", body: "Ready does not mean live. Paths stay unpinned until they are copied from the current portal." },
      { title: "Pipeline", body: "From the SEC API through the data lake, the engines, the employer twin, and the mission." },
      { title: "Three tiers", body: "SEC Open Data, other public disclosures, and the corporate private file. They are not mixed." },
      { title: "Fifteen datasets", body: "Managers, funds, policies, returns, published fees, holdings and monthly NAV. Each row says its path is not pinned until it is." },
      { title: "Scores SEC does not publish", body: "Return, fee, risk and peer scores on the sample book are marked as EPF24 calculations. Concentration and foreign exposure stay blank." },
      { title: "Fair Fee", body: "The sample negotiation book for this employer. It is not the published SEC fee." },
    ],
    before: "Do not expect this page to fetch the SEC. Read the connector line before quoting any market figure.",
    steps: [
      { title: "Read the connector status", body: "If paths are not pinned, no SEC file has been synced." },
      { title: "Walk the pipeline", body: "Know which stage a number is supposed to come from." },
      { title: "Use sample scores only with their label", body: "A score marked EPF24 is not an SEC sentence." },
      { title: "Leave blank fields blank", body: "Concentration and foreign exposure wait for datasets 11 and 12." },
    ],
    outcome: "A source map the team can defend, and no silent call to the SEC.",
    related: [
      { id: "gateway", label: "Public data" },
      { id: "fair", label: "Fair Price" },
      { id: "intel", label: "PVD Market" },
    ],
  }) },
  { title: "Best fit for this workforce, not a universal winner.", guide: g({
    code: "12",
    name: "Provider comparison",
    summary: "Rank providers for this workforce after you set the weights. The cheapest fee is not the winner by default.",
    when: "Use comparison when up to three providers must be judged for this employer, not for the market in general.",
    need: "Assets, headcount, average age, and the priorities you are willing to say out loud. The providers in this build are the sample book.",
    leave: "A ranked shortlist under your weights, and a note on whether the next step is a reprice or a market test.",
    features: [
      { title: "Weights", body: "Performance, risk, fee, service and the rest. The rank follows the weights you set." },
      { title: "Three at a time", body: "The comparison stays readable. Swap one provider rather than flooding the table." },
      { title: "Best fit", body: "The result can disagree with the lowest fee. That disagreement is the point." },
      { title: "Sample book", body: "These firms are fictional stand-ins. Do not read the result as a live quotation from a named manager." },
    ],
    before: "Write down the priorities before you look at the rank, so the weights are not tuned to a preferred winner.",
    steps: [
      { title: "Set the weights first", body: "Change a weight only when the committee would actually change it." },
      { title: "Compare three providers", body: "Include the incumbent." },
      { title: "Reject a winner that is only cheapest", body: "Read fee, fit and service together." },
      { title: "Name the next step", body: "Reprice the incumbent, or test the market. Do not award the mandate here." },
    ],
    outcome: "A weighted shortlist for this workforce, with cheapest kept visible and not automatic.",
    related: [
      { id: "market", label: "Market Test" },
      { id: "tender", label: "RFP / Tender" },
      { id: "dna", label: "Provider DNA" },
    ],
  }) },
  { title: "Will I have enough when I retire?", guide: g({
    code: "13",
    name: "Employee wealth",
    summary: "Project one member’s balance from contribution, match, return and retirement age, and show it against the target.",
    when: "Use Employee wealth when a member, or HR on their behalf, asks whether the current path reaches a usable retirement balance.",
    need: "Age, salary, contribution, match and the scenario. The chart is calculated. It is not a promised balance.",
    leave: "A projection the member can understand, and the one input that moves it most.",
    features: [
      { title: "Member file", body: "One person. In the sample, Somchai P. The chart is not the whole workforce." },
      { title: "Projection", body: "Balance by age against the target line. Deterministic, from the inputs on the page." },
      { title: "Copilot", body: "The words explain the chart. They do not invent a second balance." },
      { title: "One change at a time", body: "Contribution, retirement age, or the scenario. So the member can see what moved." },
    ],
    before: "Be clear this is one member’s illustration, not HR’s view of the company.",
    steps: [
      { title: "Confirm the member inputs", body: "Age, salary, contribution and start year before reading the end balance." },
      { title: "Read the balance against the target", body: "The dashed line is the target, not a guarantee." },
      { title: "Change one input", body: "See which lever matters. Then set it back if it was only a test." },
      { title: "Send the workforce question elsewhere", body: "A single member is not Retirement Intelligence." },
    ],
    outcome: "A member-level projection with one lever identified, and no promise of a future balance.",
    related: [
      { id: "workforce", label: "Retirement Intelligence" },
      { id: "designer", label: "EPF Designer" },
    ],
  }) },
  { title: "Is the workforce on track?", guide: g({
    code: "14",
    name: "Retirement Intelligence",
    summary: "Roll member projections into bands and see what share of the workforce is on track, without opening individual balances.",
    when: "Use Retirement Intelligence when HR or the committee asks about the workforce, not about one employee.",
    need: "The member twins in aggregate. Groups under 20 stay hidden. The target is the income-replacement line already used on this fund.",
    leave: "The share below target, the weak age band, and whether the next conversation is a design change.",
    features: [
      { title: "On track by age band", body: "Bands, not names. The weak band is the one to discuss." },
      { title: "Privacy floor", body: "Groups under 20 members are hidden so a small team cannot be identified." },
      { title: "Match simulation", body: "See what a different employer match does to the bands. It is a design test, not a fee cut." },
      { title: "Handoff to intervention", body: "A shortfall is a reason to open Intervention, not to publish member balances." },
    ],
    before: "Agree the income-replacement target before debating the percentage below it.",
    steps: [
      { title: "Start with the share below target", body: "That is the workforce question. Do not start from one outlier." },
      { title: "Open the weak band only", body: "Leave individual balances closed." },
      { title: "Test the match separately from fees", body: "A richer match and a lower fee are different decisions." },
      { title: "Take a real shortfall to Intervention", body: "If the band is fine, record that and stop." },
    ],
    outcome: "A workforce picture HR can discuss, with member balances still private.",
    related: [
      { id: "employees", label: "Employee wealth" },
      { id: "intervene", label: "Intervention" },
      { id: "designer", label: "EPF Designer" },
    ],
  }) },
  { title: "Change one assumption. The baht figure moves.", guide: g({
    code: "15",
    name: "Scenario lab",
    summary: "Move fee, asset growth or the return spread and read the employer saving and the member wealth as separate results.",
    when: "Use the lab when someone wants to see the cause of a number, one assumption at a time.",
    need: "The current scenario as the baseline. The sliders do not fetch a live market price.",
    leave: "A note of which single assumption moved which result, with the other assumption put back.",
    features: [
      { title: "Fee slider", body: "Changes the employer cost. It does not by itself repair a contribution gap." },
      { title: "Growth", body: "Changes the asset base the fee sits on." },
      { title: "Return spread", body: "Changes the member wealth scenario. Keep it labeled as a scenario." },
      { title: "Provider switch, fee only", body: "Shows the fee effect of a switch on these assumptions, without pretending the return came along for free." },
    ],
    before: "Write down the baseline before the first move, so you can return to it.",
    steps: [
      { title: "Move one slider", body: "Leave the others where they were." },
      { title: "Read both results", body: "Employer saving and member wealth. Say which one moved." },
      { title: "Reset before the next assumption", body: "Otherwise you cannot tell the cause." },
      { title: "Do not paste the experiment into the pack", body: "Only a result you are willing to defend leaves the lab." },
    ],
    outcome: "A known cause for a changed figure, or a return to the baseline.",
    related: [
      { id: "gap", label: "Value Gap" },
      { id: "mypvd", label: "My PVD" },
      { id: "twin", label: "Digital Twin" },
    ],
  }) },
  { title: "Price the market before you promise to move.", guide: g({
    code: "16",
    name: "Market Test",
    summary: "Price an anonymous profile before the company is named, then choose to renegotiate, tender, or do nothing.",
    when: "Use Market Test when the committee wants a price from the market without promising to leave the incumbent.",
    need: "A profile without the company name. Providers see the profile, not the employer. The tape in this build is the sample book.",
    leave: "Indications on one fee basis, and one decision: reprice, open a tender, or stay.",
    features: [
      { title: "Anonymous profile", body: "Assets, members and the shape of the mandate. The company name stays off." },
      { title: "One fee basis", body: "Indications are restated all-in, so 0.19% and 0.30% mean the same kind of number." },
      { title: "Negotiation pack", body: "If the incumbent can meet the range, the pack is for a reprice, not a resignation." },
      { title: "Talking points", body: "What management can say. They are not sent until someone releases them." },
    ],
    before: "Strip the company name from the profile. If the name is required, this is no longer an anonymous test.",
    steps: [
      { title: "Build the profile", body: "Include what a provider needs to price, and nothing that identifies the employer." },
      { title: "Run the test", body: "Read the indications only after they are on the same fee basis." },
      { title: "Compare with the incumbent", body: "A result inside the current fee is a reason to stay or to ask for a match, not to move." },
      { title: "Choose one path", body: "Renegotiate, open the tender, or take no action." },
    ],
    outcome: "A price for the mandate and a path, with the employer still unnamed to the market.",
    related: [
      { id: "tender", label: "RFP / Tender" },
      { id: "nego", label: "Negotiation Twin" },
      { id: "shadow", label: "Shadow Market" },
    ],
  }) },
  { title: "From requirements to a committee decision.", guide: g({
    code: "17",
    name: "RFP / Tender",
    summary: "Turn requirements into one format, score proposals with the committee’s weights, and minute the decision, including a decision to stay.",
    when: "Use the tender only after a market test or the committee has agreed to ask. Cheapest is not best.",
    need: "Locked requirements, weights, and a response deadline. The committee signs off. EPF24 drafts and normalizes.",
    leave: "A scored comparison and a minuted decision. The award is not implied by the lowest fee.",
    features: [
      { title: "Requirements", body: "What the employer will actually judge. Locked before proposals arrive." },
      { title: "Procurement agent", body: "Drafts and chases the process. It does not vote." },
      { title: "Deadline and sign-off", body: "The date proposals close, and the committee step that makes a result real." },
      { title: "Controlled bid", body: "All-in fee on one basis, so a low headline cannot hide another charge." },
      { title: "Committee weights", body: "The score uses the weights on the page. Change them in the meeting, not after the ranking is convenient." },
    ],
    before: "Confirm the committee has agreed to run a tender. A comparison is not that agreement.",
    steps: [
      { title: "Lock requirements and weights", body: "Do this before responses are open." },
      { title: "Restate every proposal into the same fields", body: "Refuse a bid that will not fit the format." },
      { title: "Score with the weights", body: "If the cheapest loses, explain the weight that did it. Do not hide the fee." },
      { title: "Minute the decision", body: "Include stay, re-run, or award. Unsigned is not decided." },
    ],
    outcome: "A committee decision on a common format, with the fee visible and not in sole charge.",
    related: [
      { id: "compare", label: "Provider comparison" },
      { id: "market", label: "Market Test" },
      { id: "switching", label: "Switching" },
    ],
  }) },
  { title: "Employers and providers, on one standard.", guide: g({
    code: "18",
    name: "Marketplace",
    summary: "Read submissions in one set of fields. Listing order is alphabetical and does not rank anyone.",
    when: "Use the marketplace to see who has put a standard submission in, before a comparison or a tender.",
    need: "Submissions restated into the shared fields. A portal fee must not change the analysis.",
    leave: "A shortlist taken into Compare or the tender. The marketplace itself is not the decision.",
    features: [
      { title: "One format", body: "Every submission is restated. A brochure order does not survive." },
      { title: "Alphabetical order", body: "Position on the page is not a rank and not a payment." },
      { title: "Submission card", body: "The fields you can compare. Missing fields stay missing." },
      { title: "No paid boost", body: "A listing fee, if one exists later, does not move the analysis." },
    ],
    before: "Ignore the visual order. Read the fields.",
    steps: [
      { title: "Read the shared fields", body: "Skip any claim that is not in the standard." },
      { title: "Note gaps", body: "A missing fee or a missing service line is a fact." },
      { title: "Make a shortlist", body: "Take it to Compare. Do not award from this page." },
      { title: "Keep the order meaningless", body: "Do not describe a firm as “first” because it is at the top." },
    ],
    outcome: "A field-by-field shortlist, with listing position ignored.",
    related: [
      { id: "compare", label: "Provider comparison" },
      { id: "tender", label: "RFP / Tender" },
    ],
  }) },
  { title: "Design the fund around the workforce.", guide: g({
    code: "19",
    name: "EPF Designer",
    summary: "Set contribution, tenure-based match and the default policy, then read employer cost and projected member wealth together.",
    when: "Use the designer when the fund’s rules are the question, not the provider’s fee.",
    need: "The workforce shape and the current contribution rules. A fee cut is a different page.",
    leave: "One design, with its employer cost and its projected member wealth side by side.",
    features: [
      { title: "Contribution", body: "What the member puts in. Shown before the match, so the two are not collapsed." },
      { title: "Match by tenure", body: "Younger, mid and longer-serving bands can differ. The cost of that choice is visible." },
      { title: "Default policy", body: "Including Life Path. The default is what most members will actually get." },
      { title: "Cost and wealth", body: "Employer cost and projected retirement wealth on the same design, so a richer match is not mistaken for a saving." },
    ],
    before: "Separate this conversation from the provider fee. A cheaper provider does not design the match.",
    steps: [
      { title: "Set contribution and match", body: "Change tenure bands only if the company would really pay them." },
      { title: "Set the default policy", body: "Assume most members stay in the default." },
      { title: "Read cost and wealth together", body: "A design that saves the employer and hurts the member is a result you must say aloud." },
      { title: "Hand a chosen design to the committee", body: "The designer does not amend the plan rules by itself." },
    ],
    outcome: "A fund design with its cost and its member effect, ready for a decision.",
    related: [
      { id: "workforce", label: "Retirement Intelligence" },
      { id: "intervene", label: "Intervention" },
      { id: "employees", label: "Employee wealth" },
    ],
  }) },
  { title: "Changing provider is a managed transition.", guide: g({
    code: "20",
    name: "Switching",
    summary: "Keep the plan, the owners and the open items for a move that the committee has already decided to make.",
    when: "Use Switching after an accepted decision to move. A better comparison is not that decision.",
    need: "The decision, the incoming provider, and the list of open items. The incumbent stays in place until the list is clear.",
    leave: "A tracked transition, or a stop if the decision was never actually made.",
    features: [
      { title: "Plan", body: "The steps of the move, in order. Winning a score is not one of them." },
      { title: "Owners", body: "Each open item has a person. An unowned item blocks the move." },
      { title: "Incumbent still in place", body: "The current provider runs the fund until the checklist says otherwise." },
      { title: "No action remains available", body: "If the decision is soft, send the work back to the tender. Do not start a move." },
    ],
    before: "Find the minuted decision. If it does not exist, leave this page.",
    steps: [
      { title: "Confirm the decision is real", body: "A shortlist is not a decision to move." },
      { title: "Assign every open item", body: "Owner and status. Do not start with the announcement." },
      { title: "Keep the incumbent until the list is clear", body: "Members should not be between providers." },
      { title: "Stop if an item cannot close", body: "Record the block. Do not improvise the move." },
    ],
    outcome: "A transition with owners, or a deliberate return to the current provider.",
    related: [
      { id: "tender", label: "RFP / Tender" },
      { id: "committee", label: "Committee AI" },
    ],
  }) },
  { title: "The fund’s document record.", guide: g({
    code: "21",
    name: "Documents",
    summary: "Hold the agreement, the fee schedule, factsheets and minutes, and use a file only after it is reviewed.",
    when: "Use Documents when a number on another page needs a source, or when a new provider report arrives.",
    need: "The file itself. An extracting row is not yet a source.",
    leave: "A reviewed document that Fee X-Ray and the committee pack are allowed to use.",
    features: [
      { title: "The record", body: "Contract, fee schedule, factsheet, minutes, policy, regulation. Each has a status." },
      { title: "Upload", body: "A new file starts as extracting. Wait for reviewed." },
      { title: "Status", body: "Reviewed, approved, monitored, extracting. Quote only the first two as settled." },
      { title: "Not a price", body: "A document is source material. It is not itself a market price." },
    ],
    before: "Know which downstream page needs the file, so you upload the right one.",
    steps: [
      { title: "Upload the agreement, the fee schedule and the latest factsheet", body: "Those three unlock Benchmark and Fee X-Ray." },
      { title: "Wait for reviewed", body: "Do not quote an extracting file." },
      { title: "Point the committee at the file", body: "A claim in the pack should name the document." },
      { title: "Keep factsheet and contract distinct", body: "They may disagree. That disagreement is useful. Do not average them." },
    ],
    outcome: "A reviewed source for the fee and the committee, with draft files still marked draft.",
    related: [
      { id: "xray", label: "Fee X-Ray" },
      { id: "bench", label: "Benchmark" },
      { id: "committee", label: "Committee AI" },
    ],
  }) },
  { title: "SEC Open Data is the raw layer.", guide: g({
    code: "22",
    name: "Public data",
    summary: "See which public sources exist, which are loaded, and which the page is deliberately not calling.",
    when: "Use Public data when someone asks whether a figure is from the SEC, from the register, or from the employer’s own file.",
    need: "Nothing to type. This screen does not pull the SEC. Sync waits for the current portal’s base URL, header and key.",
    leave: "A status for each source, and a reminder that a published fee does not replace the negotiated fee.",
    features: [
      { title: "SEC Open Data", body: "Free for commercial and personal use. The connector is ready and the dataset paths are not pinned, so nothing is live yet." },
      { title: "Register lists", body: "Companies and employer funds already loaded into the workspace, separate from SEC factsheets." },
      { title: "Market sources not connected", body: "SET, ThaiBMA and BOT are named so their absence is visible." },
      { title: "Private lanes", body: "The employer contract and tender quotations stay out of the public store." },
    ],
    before: "Do not refresh this page expecting a new SEC pull. It will not make one.",
    steps: [
      { title: "Read the status column", body: "Loaded, ready, or not connected. Do not upgrade a status in conversation." },
      { title: "Keep published fees in the public lane", body: "They do not overwrite Fee X-Ray." },
      { title: "Send architecture questions to the intelligence network", body: "The pipeline and the fifteen datasets live there." },
      { title: "Leave the key off the page", body: "The browser does not hold the subscription key." },
    ],
    outcome: "A honest map of what is loaded, and no accidental call to the SEC.",
    related: [
      { id: "network", label: "Intelligence network" },
      { id: "intel", label: "PVD Market" },
      { id: "xray", label: "Fee X-Ray" },
    ],
  }) },
  { title: "Trust, methodology and the workspace.", guide: g({
    code: "23",
    name: "Admin",
    summary: "See how the workspace treats fees, returns and decisions, and where the monitoring thresholds live.",
    when: "Use Admin when a number’s lane is disputed, or when a Watch threshold needs to be confirmed.",
    need: "The methodology notes on the page. Admin does not invent a return.",
    leave: "Agreement on which lane a figure belongs to, and the thresholds Watch will use.",
    features: [
      { title: "Product", body: "What this workspace is: a decision aid for one provident fund, not a live bidding system." },
      { title: "Monitoring thresholds", body: "The rules EPF Watch applies. Change them here, not inside an alert." },
      { title: "Trust disclosures", body: "SEC-reported data, the contract, and EPF24 calculations stay in separate lanes." },
      { title: "No new performance", body: "Nothing on Admin creates a return for a real fund." },
    ],
    before: "Come here to check a rule, not to produce a client figure.",
    steps: [
      { title: "Read the lane for the disputed number", body: "SEC, contract, or calculation. Pick one." },
      { title: "Confirm the Watch thresholds", body: "If an alert surprised the committee, the rule is the thing to read." },
      { title: "Do not blend lanes to make a smoother story", body: "A published fee and a negotiated fee stay apart." },
      { title: "Return to the page that holds the figure", body: "Admin explains the rule. It does not replace the source." },
    ],
    outcome: "A shared rule for how figures are labeled, and thresholds the committee recognizes.",
    related: [
      { id: "watch", label: "EPF Watch" },
      { id: "gateway", label: "Public data" },
      { id: "home", label: "Dashboard" },
    ],
  }) },
  { title: "The intelligence and exchange layer.", guide: g({
    code: "24",
    name: "AGI Mission",
    summary: "Run a mission on the fund record. The engines calculate, the model explains, and a person still decides.",
    when: "Use AGI Mission when the question is a defined job from the catalog, including the job that concludes the current fund is already competitive.",
    need: "The open file, the mission, and the mode: single, team, or swarm. The model may only see what that mode allows.",
    leave: "A mission result with drivers, source, risks, and the human step required. No letter goes out by itself.",
    features: [
      { title: "Mission runner", body: "One job at a time, with the steps the mode is allowed to take." },
      { title: "What each mode can see", body: "Single, team and swarm are different permissions, not different adjectives." },
      { title: "Entry missions", body: "The short list to start from, before the full catalog." },
      { title: "Catalog", body: "The 120 missions, grouped. A mission states its work and its measure." },
      { title: "Stop rule", body: "A valid result is that the current arrangement remains competitive." },
    ],
    before: "Pick the mission that matches the decision in front of the committee. Do not start from the most dramatic one.",
    steps: [
      { title: "Choose the mission and the mode", body: "Confirm what that mode is allowed to see." },
      { title: "Run it and read the drivers", body: "Source, assumptions, alternatives and risks. Not only the headline baht." },
      { title: "Accept a no-action result", body: "If the incumbent is still competitive, record that." },
      { title: "Leave release to a person", body: "The mission does not send the letter." },
    ],
    outcome: "A mission record the committee can accept, reject, or park, with the current provider still in place until they say otherwise.",
    related: [
      { id: "cio", label: "Autonomous CIO" },
      { id: "home", label: "Dashboard" },
      { id: "committee", label: "Committee AI" },
    ],
  }) },
  { title: "One action, not fifty alerts.", guide: g({
    code: "25",
    name: "Autonomous CIO",
    summary: "Collapse the watch-list into one next action, then let a challenger try to knock it down.",
    when: "Use Autonomous CIO when the committee is tired of alerts and wants the single thing worth doing.",
    need: "The fund record the agents are allowed to see. A person still decides.",
    leave: "One action, or a rejected action, with the reason written down.",
    features: [
      { title: "One action", body: "The proposal. Not a queue of fifty notices." },
      { title: "Why this, and not a switch", body: "The case for the action, including the case for staying." },
      { title: "Challenger", body: "A second pass that tries to defeat the conclusion. If it succeeds, stop." },
      { title: "Watching, not paging", body: "What is being observed quietly, so the action is not everything the agents saw." },
    ],
    before: "Agree that one action is what you want. If you need the full exception list, use EPF Watch.",
    steps: [
      { title: "Read the single action", body: "Ignore the temptation to add three more." },
      { title: "Read the challenger", body: "If it knocks the action down, do not override it for drama." },
      { title: "Accept no action when it holds", body: "A competitive incumbent is a successful result." },
      { title: "Minute the choice", body: "The CIO proposes. The committee records." },
    ],
    outcome: "One accepted or rejected action, with the challenger’s reason kept.",
    related: [
      { id: "watch", label: "EPF Watch" },
      { id: "mission", label: "AGI Mission" },
      { id: "committee", label: "Committee AI" },
    ],
  }) },
  { title: "The transaction graph is the moat.", guide: g({
    code: "26",
    name: "Market Brain",
    summary: "Separate public returns from the private tape of what employers were offered, what they negotiated, and what they chose.",
    when: "Use Market Brain when the question is why EPF24’s record is different from a factsheet.",
    need: "The sample transaction book. It is not a live tape of the market.",
    leave: "A clear statement of what is public, what is private, and what a competitor could copy.",
    features: [
      { title: "Defensibility stack", body: "Which layers are public and which exist only because employers ran a process here." },
      { title: "What a competitor can copy", body: "The model and the public data. Not the tape of real negotiations." },
      { title: "How the book compounds", body: "Each completed test makes the next range sharper. This build is still the sample." },
      { title: "Anonymized transactions", body: "The rows you can read without naming the employer." },
    ],
    before: "Do not describe the sample book as a thousand live companies.",
    steps: [
      { title: "Separate the public layer from the private tape", body: "Returns can be public. The price an employer was offered is not." },
      { title: "Read what was offered, accepted, and what followed", body: "A return without the decision is the thin layer." },
      { title: "Say the tape is the sample", body: "Until more employers run a test, the book does not get thicker by itself." },
      { title: "Use Fair Price for a number", body: "This page explains the moat. It does not quote the clearing fee." },
    ],
    outcome: "A shared understanding of what the record contains, and what it does not.",
    related: [
      { id: "fair", label: "Fair Price" },
      { id: "network", label: "Intelligence network" },
      { id: "outcome", label: "Outcome Engine" },
    ],
  }) },
  { title: "A virtual tender, running without a letter to anyone.", guide: g({
    code: "27",
    name: "Shadow Market",
    summary: "Ask what this mandate might clear if it went to market today, without contacting anyone.",
    when: "Use Shadow Market before a real test, or when the likely answer is to do nothing.",
    need: "The open mandate’s size and shape. No letter is generated.",
    leave: "A clearing range and a yes or no on whether a real test is worth running.",
    features: [
      { title: "Current provider", body: "Where the incumbent sits, so the shadow has something to beat." },
      { title: "Better-fit alternatives", body: "Names from the sample book that the shadow thinks could fit. Not live bids." },
      { title: "Clearing question", body: "What the mandate might clear. Sometimes the answer is inside the current fee." },
      { title: "No outbound mail", body: "Nothing on this page is an instruction that has been sent." },
    ],
    before: "Confirm you do not want providers contacted. If you do, use Market Test.",
    steps: [
      { title: "Run the shadow on the open mandate", body: "Keep the company name out of any note you export." },
      { title: "Read the range against the incumbent", body: "Inside the current fee means do not write a letter." },
      { title: "Decide whether a real test is justified", body: "A shadow is not the test." },
      { title: "Record no action when that is the result", body: "Say it in the committee pack if the question was asked." },
    ],
    outcome: "A private range and a decision to test or to stop, with no provider contacted.",
    related: [
      { id: "market", label: "Market Test" },
      { id: "fair", label: "Fair Price" },
      { id: "cio", label: "Autonomous CIO" },
    ],
  }) },
  { title: "What this mandate has actually cleared.", guide: g({
    code: "28",
    name: "Fair Price",
    summary: "Show the published fee range and the EPF24 observed range apart, and never average them.",
    when: "Use Fair Price when someone asks what a mandate of this size has actually cleared, as distinct from a factsheet.",
    need: "Assets for the open mandate. The observed range is the sample negotiation book, not a live tape.",
    leave: "Two ranges, labeled, and a refusal to blend them into one “market fee.”",
    features: [
      { title: "Published range", body: "What public material can support. It is not the price this employer negotiated." },
      { title: "EPF24 range", body: "What the sample book has seen for a mandate of this size." },
      { title: "No blend", body: "The two ranges stay on two lines. An average would hide which source you mean." },
      { title: "Size matters", body: "The curve moves with assets. Do not reuse a small-fund fee on a large mandate." },
    ],
    before: "Know the asset figure you are pricing. Say the observed range is the sample book.",
    steps: [
      { title: "Read the published range", body: "Call it published." },
      { title: "Read the EPF24 range", body: "Call it observed, and sample, until the tape is live." },
      { title: "Do not average them", body: "If a slide has one fee, it is the wrong slide." },
      { title: "Take the pair into the negotiation", body: "Negotiation Twin uses the range. Fair Price only states it." },
    ],
    outcome: "Two labeled ranges for this mandate size, unblended.",
    related: [
      { id: "nego", label: "Negotiation Twin" },
      { id: "network", label: "Intelligence network" },
      { id: "xray", label: "Fee X-Ray" },
    ],
  }) },
  { title: "Which provider fits which employer.", guide: g({
    code: "29",
    name: "Provider DNA",
    summary: "Judge fit from pricing behavior, service after the win, and the workforce a firm is good at. A return is only one field.",
    when: "Use Provider DNA when a shortlist needs a fit test, not another performance table.",
    need: "The employer’s shape: size, workforce, and what “good service” means here. The firms on this page are fictional.",
    leave: "A fit note the committee can use, without insulting a real named manager.",
    features: [
      { title: "Fit, not a return", body: "DNA is behavior and the kind of employer the firm serves well." },
      { title: "After the win", body: "Service once the mandate is awarded, not the pitch." },
      { title: "Sample firms", body: "The names are the fictional book. Do not map them onto real AMCs." },
      { title: "Drop a mismatch", body: "A strong firm for a different workforce is not a strong firm for this one." },
    ],
    before: "Describe this employer before opening a provider. Fit has no meaning without that.",
    steps: [
      { title: "Write the workforce and the service need", body: "One paragraph. Use it as the test." },
      { title: "Read behavior before return", body: "A good five-year number does not answer service." },
      { title: "Drop a provider aimed at a different employer", body: "Say why, in the note." },
      { title: "Keep the language inside the sample book", body: "Do not publish these notes as a view of a real firm." },
    ],
    outcome: "A fit shortlist for this kind of employer, clearly marked as the sample book.",
    related: [
      { id: "compare", label: "Provider comparison" },
      { id: "nego", label: "Negotiation Twin" },
    ],
  }) },
  { title: "What this provider has accepted before.", guide: g({
    code: "30",
    name: "Negotiation Twin",
    summary: "See how far a provider has moved on comparable mandates, and draft a counterproposal that stays inside that range.",
    when: "Use Negotiation Twin when the path is a reprice of the incumbent, or a push on a bidder, and you need the range rather than a slogan.",
    need: "The provider, the mandate size, and Fair Price. The letter stays a draft until the secretary releases it.",
    leave: "A draft inside the observed range, unsent.",
    features: [
      { title: "Accepted range", body: "Where this firm has moved before on a comparable mandate in the sample book." },
      { title: "Draft", body: "The counterproposal. Easy to copy, useless if it ignores the range." },
      { title: "Release gate", body: "Nothing is sent without the committee secretary." },
      { title: "Stay is allowed", body: "If the incumbent is already inside the range, the draft can be a decision not to send." },
    ],
    before: "Have Fair Price open in your notes so the draft is not a round number from memory.",
    steps: [
      { title: "Read the range", body: "Do not open the letter first." },
      { title: "Draft inside the range", body: "A number outside it needs a reason, not confidence." },
      { title: "Leave it unsent", body: "The secretary releases. This page does not." },
      { title: "Record a decision not to send", body: "If the current price already matches, that is the result." },
    ],
    outcome: "An unsent draft, or a recorded decision that no letter is needed.",
    related: [
      { id: "fair", label: "Fair Price" },
      { id: "market", label: "Market Test" },
      { id: "committee", label: "Committee AI" },
    ],
  }) },
  { title: "The whole fund, not one member.", guide: g({
    code: "31",
    name: "Digital Twin",
    summary: "Run one shock on the employer’s fund — fees, a switch, Life Path, the match, or a market move — and read the fund-level result.",
    when: "Use the corporate twin when the question is the whole fund. Member balances stay private.",
    need: "The employer file: assets, fees, policy and workforce. Run one shock at a time.",
    leave: "The fund-level effect of that one shock, noted before the next shock is run.",
    features: [
      { title: "The whole fund", body: "Assets, fees, policies and the workforce as one model. Not one member’s login." },
      { title: "Shocks", body: "Switch, fee cut, Life Path, a higher match, a market move. Each is separate." },
      { title: "Result card", body: "What that shock does at fund level. Read it before stacking another." },
      { title: "Privacy", body: "Member twins are not opened from this page." },
    ],
    before: "Pick one question. A pile of shocks run together cannot be explained.",
    steps: [
      { title: "Choose one shock", body: "Fees, switch, policy, match, or market." },
      { title: "Read the fund-level result", body: "Write down what moved before you touch the next control." },
      { title: "Keep member balances closed", body: "If the question is one person, use Employee wealth." },
      { title: "Run the next shock only after the first is noted", body: "Otherwise the committee hears a blend." },
    ],
    outcome: "One explained fund-level scenario, with members still aggregated.",
    related: [
      { id: "lab", label: "Scenario lab" },
      { id: "workforce", label: "Retirement Intelligence" },
      { id: "intervene", label: "Intervention" },
    ],
  }) },
  { title: "What should we do about the shortfall?", guide: g({
    code: "32",
    name: "Intervention",
    summary: "Lay out what to do about the share of members projected below the income-replacement target, including a path that does not need a large new match.",
    when: "Use Intervention after Retirement Intelligence has shown a real shortfall.",
    need: "The shortfall, the cost of each path, and the workforce bands. Do not start here from a fee complaint.",
    leave: "A costed path, which may be a modest design change rather than a large new match.",
    features: [
      { title: "The shortfall", body: "The share below the 60% income-replacement target. That is the problem statement." },
      { title: "Paths", body: "Including the one that does not ask for a large new match." },
      { title: "Cost", body: "Each path has an employer cost. A path without a cost is not a proposal." },
      { title: "Not a fee cut", body: "A lower provider fee does not, by itself, close a contribution gap." },
    ],
    before: "Bring the weak band from Retirement Intelligence. If you do not have it, go there first.",
    steps: [
      { title: "State the share below target", body: "Use the workforce figure, not an anecdote." },
      { title: "Lay out every path, including the modest one", body: "Do not open with the most expensive match." },
      { title: "Cost each path", body: "Employer cost beside the change in the projected shortfall." },
      { title: "Pick one, or pick none", body: "A decision not to add cost is allowed if the shortfall is accepted." },
    ],
    outcome: "A costed response to the shortfall, or a recorded decision to leave the design as it is.",
    related: [
      { id: "workforce", label: "Retirement Intelligence" },
      { id: "designer", label: "EPF Designer" },
      { id: "twin", label: "Digital Twin" },
    ],
  }) },
  { title: "What actually happened after the decision.", guide: g({
    code: "33",
    name: "Outcome Engine",
    summary: "Look at what followed a fee cut, a switch, or a decision to stay. Without a history tape, say the rows are the sample record.",
    when: "Use the outcome engine when the committee wants evidence from after a decision, not another prediction.",
    need: "Closed cases. In this build they are the sample book. A competitor with no history cannot answer this, and neither can an empty tape.",
    leave: "What happened, labeled as sample until a real case is in the book, and the question the loop can now answer.",
    features: [
      { title: "Closed cases", body: "The decisions that have an after. Sample rows are marked by living on this page’s sample book." },
      { title: "The loop", body: "Observe, predict, recommend, execute, measure, learn. A missing measure means the loop is open." },
      { title: "Questions only history answers", body: "What the fee cut did. What the switch did. What staying did." },
      { title: "This book, so far", body: "How thin the record still is. Do not inflate it." },
    ],
    before: "Say “sample record” before you quote a case in a meeting.",
    steps: [
      { title: "Pick a past decision type", body: "Fee cut, switch, or stay." },
      { title: "Read what followed", body: "Fund and members. Not the pitch that preceded it." },
      { title: "Label the tape", body: "If it is only the sample, the sentence must say so." },
      { title: "Do not invent the missing case", body: "An empty after is not a success story." },
    ],
    outcome: "A sourced after-action note, or an honest gap where the tape is empty.",
    related: [
      { id: "brain", label: "Market Brain" },
      { id: "committee", label: "Committee AI" },
    ],
  }) },
  { title: "A continuous market for mandates.", guide: g({
    code: "34",
    name: "Exchange",
    summary: "Post an anonymous mandate, take bids in one format, and read the tape of ask, bid, counter and winner.",
    when: "Use the exchange when the mandate should meet qualified providers continuously, not through a brochure request.",
    need: "An anonymous mandate and one submission format. The company name stays off the tape you show providers.",
    leave: "A tape the committee can read before any award.",
    features: [
      { title: "Anonymous mandate", body: "What providers are allowed to see. Identity stays with the employer." },
      { title: "One format", body: "Ask, bid and counter in the same fields. A narrative pitch does not replace them." },
      { title: "The tape", body: "Ask, bid, counter, winner, and what followed. That sequence is the record." },
      { title: "Not a brochure", body: "A request for marketing material is a different, weaker process." },
    ],
    before: "Write the mandate so a provider can price it without learning the company name.",
    steps: [
      { title: "Post the mandate without the name", body: "Check the profile the way you would check Market Test." },
      { title: "Take bids only in the format", body: "Send back anything that will not fit." },
      { title: "Read the tape before an award", body: "Ask, bid, counter, then winner. Do not skip to the name." },
      { title: "Minute the award separately", body: "The tape is evidence. The committee still decides." },
    ],
    outcome: "A readable tape and, only if the committee says so, an award.",
    related: [
      { id: "market", label: "Market Test" },
      { id: "tender", label: "RFP / Tender" },
      { id: "marketplace", label: "Marketplace" },
    ],
  }) },
];

export function pageGuide(title: string): Guide {
  const found = GUIDES.find((row) => row.title === title);
  if (found) return found.guide;
  if (title.includes("provident fund is still competitive")) return HOME;
  return g({
    code: "—",
    name: "This page",
    summary: `Read “${title}” as a decision aid for one provident fund.`,
    when: "Use this page when its headline is the question the committee is actually asking.",
    need: "The open employer file, and a clear lane for each figure: SEC, the contract, or an EPF24 calculation.",
    leave: "A labeled result and a next step, including the option to leave the current arrangement in place.",
    features: [
      { title: "The question", body: "The headline is the job of the page. Do not make it answer a different one." },
      { title: "The lanes", body: "Published data, the employer’s contract, and calculated scenarios stay apart." },
      { title: "The sample", body: "Until a live file replaces it, the Rattana book is a scenario." },
      { title: "The stop rule", body: "No action is a complete outcome when the current fund is still competitive." },
    ],
    before: "Name the employer file and the lane of the number you are about to use.",
    steps: [
      { title: "Read the headline and the source", body: "Do not quote a number before you know its lane." },
      { title: "Separate SEC, contract, and calculation", body: "Say which one this page is showing." },
      { title: "Take one next step", body: "Open the related page that can carry the decision." },
      { title: "Record no action if that is the result", body: "A switch is not required to finish the page." },
    ],
    outcome: "A sourced note the committee can use, with no letter sent.",
    related: [
      { id: "home", label: "Dashboard" },
      { id: "settings", label: "Admin" },
    ],
  });
}
